import { validateLumpsumInput } from "@/features/calculators/lumpsum/lumpsum-schema"
import type { LumpsumDurationUnit, LumpsumInput } from "@/features/calculators/lumpsum/lumpsum-types"
import { buildCalculatorUrl } from "@/lib/calculator-url"
export const LUMPSUM_DEFAULT_INPUT: LumpsumInput = { initialInvestment: 100_000, annualReturnRate: 12, duration: 10, durationUnit: "years" }
type SearchInput = URLSearchParams | Readonly<Record<string, string | string[] | undefined>>
function read(search: SearchInput, key: string) { const value = search instanceof URLSearchParams ? search.get(key) ?? undefined : search[key]; return Array.isArray(value) ? value[0] : value }
export function parseLumpsumUrlState(search: SearchInput, defaults: LumpsumInput = LUMPSUM_DEFAULT_INPUT): LumpsumInput { const candidate: LumpsumInput = { initialInvestment: read(search,"amount") === undefined ? defaults.initialInvestment : Number(read(search,"amount")), annualReturnRate: read(search,"return") === undefined ? defaults.annualReturnRate : Number(read(search,"return")), duration: read(search,"duration") === undefined ? defaults.duration : Number(read(search,"duration")), durationUnit: (read(search,"unit") ?? defaults.durationUnit) as LumpsumDurationUnit }; const validation=validateLumpsumInput(candidate); if(validation.success)return validation.data; const fallback={...candidate,initialInvestment:validation.errors.initialInvestment?defaults.initialInvestment:candidate.initialInvestment,annualReturnRate:validation.errors.annualReturnRate?defaults.annualReturnRate:candidate.annualReturnRate,duration:validation.errors.duration?defaults.duration:candidate.duration,durationUnit:validation.errors.durationUnit?defaults.durationUnit:candidate.durationUnit}; const checked=validateLumpsumInput(fallback); return checked.success?checked.data:defaults }
export function serializeLumpsumUrlState(input:LumpsumInput){if(!validateLumpsumInput(input).success)throw new RangeError("Invalid Lumpsum URL state");return new URLSearchParams({amount:String(input.initialInvestment),return:String(input.annualReturnRate),duration:String(input.duration),unit:input.durationUnit})}
export function buildLumpsumCalculatorUrl(input:LumpsumInput,origin?:string){return buildCalculatorUrl("/finance/lumpsum-calculator",Object.fromEntries(serializeLumpsumUrlState(input)),origin)}
