import type { CalculatorKnowledgeContent } from "@/types/calculator-content"

export const lumpsumKnowledgeContent = {
  title: "Understand your lumpsum projection", description: "Explore how a one-time amount may grow under a consistent assumed return.",
  sections: [
    { id: "lumpsum-how-to-use", title: "How to use the Lumpsum calculator", type: "input-guide", content: [{ type: "list", style: "numbered", items: ["Enter the one-time investment amount.", "Add an expected annual return as an assumption.", "Choose the duration and review initial amount, projected gains, and estimated value."] }] },
    { id: "lumpsum-input-effects", title: "How amount, return, and duration affect growth", type: "how-it-works", content: [{ type: "paragraph", text: "A larger starting amount scales the result. Higher return assumptions and longer durations increase projected growth, but neither predicts actual market performance." }] },
    { id: "lumpsum-compounding", title: "How compound growth works", type: "how-it-works", content: [{ type: "paragraph", text: "Compounding means projected returns remain invested and may generate further returns. The calculator applies smooth annual growth; real markets fluctuate." }] },
    { id: "lumpsum-value", title: "Initial investment versus estimated returns", type: "interpretation", content: [{ type: "paragraph", text: "The initial investment is the amount entered. Estimated returns are the projected future value minus that amount, not a guaranteed profit." }] },
    { id: "lumpsum-duration", title: "Effect of investment duration", type: "interpretation", content: [{ type: "paragraph", text: "Additional time gives compounding more periods to operate. It also leaves the investment exposed to market movement for longer, so actual outcomes remain uncertain." }] },
    { id: "lumpsum-benefits", title: "Benefits and common use cases", type: "benefits", content: [{ type: "list", style: "bullet", items: ["Explore the possible growth of an amount already available.", "Compare durations and assumptions consistently.", "Separate starting capital from projected gains."] }] },
    { id: "lumpsum-limitations", title: "Limitations and assumptions", type: "limitations", content: [{ type: "callout", variant: "warning", title: "Returns vary", text: "The model excludes market volatility, inflation, taxes, fees, and product rules unless stated. It does not recommend when to enter the market." }] },
    { id: "lumpsum-mistakes", title: "Common lumpsum calculation mistakes", type: "common-mistakes", content: [{ type: "list", style: "bullet", items: ["Treating an assumed return as certain.", "Ignoring inflation, fees, and taxes.", "Confusing simple interest with compound growth.", "Selecting a duration that does not match the intended use of the money."] }] },
    { id: "lumpsum-tips", title: "Practical tips", type: "practical-tips", content: [{ type: "list", style: "bullet", items: ["Compare several return assumptions.", "Review both nominal value and inflation’s possible effect.", "Keep liquidity needs separate from the projection.", "Use the schedule to understand how time changes the estimate."] }] },
    { id: "lumpsum-comparison", title: "Lumpsum versus SIP", type: "comparison", content: [{ type: "table", caption: "Lumpsum and SIP investment comparison", headers: ["Factor", "Lumpsum", "SIP"], rows: [["Contribution pattern", "One-time amount", "Regular amounts"], ["Entry timing", "Capital enters at one point", "Capital enters across multiple dates"], ["May suit users who", "Have an amount available", "Invest from recurring cash flow"], ["Outcome varies with", "Market path, duration, fees, and taxes", "Market path, contribution timing, fees, and taxes"]] }] },
  ],
  relatedLinks: [{ title: "SIP Calculator", description: "Explore regular investments.", href: "/finance/sip-calculator" }, { title: "FD Calculator", description: "Estimate deposit maturity.", href: "/finance/fd-calculator" }, { title: "RD Calculator", description: "Explore monthly deposits.", href: "/finance/rd-calculator" }, { title: "EMI Calculator", description: "Estimate loan repayments.", href: "/finance/emi-calculator" }],
} as const satisfies CalculatorKnowledgeContent
