import { calculateInflationFutureCost,calculateInflationPresentValue } from "./calculate-inflation";import { formatIndianCurrency } from "@/lib/formatters";import type { CalculatorKnowledgeContent } from "@/types/calculator-content"
const comparisonFutureCost=calculateInflationFutureCost({mode:"futureCost",amount:100_000,annualInflationRate:6,years:10})
const comparisonPresentValue=calculateInflationPresentValue({mode:"presentValue",amount:100_000,annualInflationRate:6,years:10})
export const inflationKnowledgeContent={title:"Understand an inflation projection",description:"See how future cost and present value relate, how deflation and zero inflation are handled, and why the result remains an assumption, not a forecast.",sections:[
{id:"definition",title:"What this calculator estimates",type:"overview",content:[{type:"paragraph",text:"Inflation is the rate at which prices rise over time, reducing what a fixed amount of money can buy. This calculator projects that effect in two directions: forward, to estimate a future cost, or backward, to estimate what a future amount is worth in today's purchasing power."}]},
{id:"inputs",title:"Inputs used",type:"input-guide",content:[{type:"list",style:"numbered",items:["Choose future cost mode or present value / purchasing power mode.","Enter the amount: a current amount in future cost mode, or a future amount in present value mode.","Enter an assumed annual inflation rate, which may be negative to model deflation.","Enter a whole-number duration in years."]}]},
{id:"compounding",title:"How the rate compounds",type:"how-it-works",content:[{type:"callout",variant:"important",title:"Annual compounding",text:"The entered rate compounds once per year: the factor is (1 + rate) raised to the power of the number of years. A negative rate is a fully valid input and is not clamped to zero; it simply pulls the factor below 1, so future cost falls and present value rises. A 0% rate leaves the amount unchanged in either mode."}]},
{id:"modes",title:"Future cost and present value modes",type:"how-it-works",content:[{type:"paragraph",text:"Future cost mode multiplies the current amount by the compounding factor to show what an equivalent purchase might cost later. Present value mode divides a future amount by the same factor to show what that fixed future sum is worth in today's purchasing power. The two modes are inverses of the same underlying formula."}]},
{id:"comparison",title:"Future cost versus present value",type:"comparison",content:[{type:"table",caption:"Same ₹1,00,000 amount, 6% assumed annual inflation, 10 years",headers:["Mode","Input amount","Result"],rows:[["Future cost","₹1,00,000 today",formatIndianCurrency(comparisonFutureCost.futureValue)],["Present value","₹1,00,000 in 10 years",formatIndianCurrency(comparisonPresentValue.presentValue)]]}]},
{id:"interpretation",title:"How to read the results",type:"interpretation",content:[{type:"paragraph",text:"In future cost mode, the total inflation impact is the projected increase (or, under deflation, decrease) in cost. In present value mode, the purchasing power change is the difference between the future amount's face value and what it is worth today; a positive change means erosion from inflation, and a negative change means a purchasing-power gain from deflation."}]},
{id:"mistakes",title:"Common mistakes",type:"common-mistakes",content:[{type:"list",style:"bullet",items:["Assuming this uses actual Consumer Price Index data rather than the single rate entered.","Confusing future cost mode (money going forward) with present value mode (money coming back to today).","Treating a single constant rate as a guaranteed or personalised forecast.","Using this for Cost Inflation Index or other statutory tax-indexation purposes, which it does not implement."]}]},
{id:"tips",title:"Practical scenario checks",type:"practical-tips",content:[{type:"list",style:"bullet",items:["Compare a modest and a high inflation assumption for the same amount and duration.","Try a small negative rate to see how deflation is handled without any special input.","Use present value mode to see what a long-term savings target is really worth today."]}]},
{id:"benefits",title:"Potential planning benefits",type:"benefits",content:[{type:"list",style:"bullet",items:["Makes the erosion of purchasing power explicit rather than implicit.","Lets a future cost and today's equivalent value be compared side by side.","Supports both inflation and deflation scenarios with the same consistent formula."]}]},
{id:"limits",title:"Assumptions and limitations",type:"limitations",content:[{type:"list",style:"bullet",items:["A single constant annual rate is an educational assumption, not a personalised or CPI-linked forecast, and real inflation varies year to year.","This calculator does not look up real-time or historical Consumer Price Index data.","It does not implement the Cost Inflation Index or any other statutory tax-indexation rule.","This is not an economic forecast, investment advice, or a guarantee of future prices."]}]}
],relatedLinks:[{title:"Inflation meaning",description:"Read the concise glossary definition.",href:"/glossary/inflation"},{title:"SIP Calculator",description:"Estimate the future value of regular contributions.",href:"/finance/sip-calculator"},{title:"Lumpsum Calculator",description:"Estimate the future value of a one-time investment.",href:"/finance/lumpsum-calculator"},{title:"CAGR Calculator",description:"Understand annualised growth.",href:"/finance/cagr-calculator"}]} as const satisfies CalculatorKnowledgeContent
