import { describe,expect,it } from "vitest"
import { parseAndValidateSWPForm,parseSWPNumericText,validateSWPInput } from "../swp-schema"
const valid={initialInvestment:5_000_000,monthlyWithdrawal:35_000,expectedAnnualReturn:8,withdrawalMode:"fixedDuration" as const,durationYears:20}
describe("SWP validation",()=>{
  it("strictly parses plain decimals",()=>{for(const value of ["0","0.01",".5","1000","7.50"])expect(parseSWPNumericText(value)).toBe(Number(value));for(const value of [""," "," 10","10 ","1,000","₹1000","+10","-10","1e3","1.",".","NaN","Infinity"])expect(parseSWPNumericText(value)).toBeNull()})
  it("accepts both withdrawal modes",()=>{expect(validateSWPInput(valid).success).toBe(true);expect(validateSWPInput({...valid,withdrawalMode:"untilExhausted"}).success).toBe(true)})
  it("accepts boundary values",()=>{expect(validateSWPInput({...valid,initialInvestment:1_000}).success).toBe(true);expect(validateSWPInput({...valid,initialInvestment:100_000_000}).success).toBe(true);expect(validateSWPInput({...valid,monthlyWithdrawal:100}).success).toBe(true);expect(validateSWPInput({...valid,expectedAnnualReturn:0}).success).toBe(true);expect(validateSWPInput({...valid,expectedAnnualReturn:50}).success).toBe(true);expect(validateSWPInput({...valid,durationYears:1}).success).toBe(true);expect(validateSWPInput({...valid,durationYears:50}).success).toBe(true)})
  it.each([{initialInvestment:999},{initialInvestment:100_000_001},{monthlyWithdrawal:99},{monthlyWithdrawal:10_000_001},{expectedAnnualReturn:-1},{expectedAnnualReturn:51},{durationYears:1.5},{durationYears:0},{durationYears:51}])("rejects invalid input %o",change=>expect(validateSWPInput({...valid,...change}).success).toBe(false))
  it("rejects invalid mode and non-finite values",()=>{expect(validateSWPInput({...valid,withdrawalMode:"other" as never}).success).toBe(false);expect(validateSWPInput({...valid,initialInvestment:Infinity}).success).toBe(false);expect(validateSWPInput({...valid,monthlyWithdrawal:Number.NaN}).success).toBe(false)})
  it("still bounds-checks durationYears when the mode is untilExhausted, since the value is preserved for later mode switches",()=>{expect(validateSWPInput({...valid,withdrawalMode:"untilExhausted",durationYears:0}).success).toBe(false);expect(validateSWPInput({...valid,withdrawalMode:"untilExhausted",durationYears:10}).success).toBe(true)})
  it("rejects malformed form text without losing field-specific errors",()=>{const result=parseAndValidateSWPForm({initialInvestment:"1e3",monthlyWithdrawal:" ",expectedAnnualReturn:"8 ",withdrawalMode:"fixedDuration",durationYears:"1e1"});expect(result.success).toBe(false);if(!result.success)expect(Object.keys(result.errors).sort()).toEqual(["durationYears","expectedAnnualReturn","initialInvestment","monthlyWithdrawal"])})
  it("parses a valid form",()=>{const result=parseAndValidateSWPForm({initialInvestment:"5000000",monthlyWithdrawal:"35000",expectedAnnualReturn:"8",withdrawalMode:"fixedDuration",durationYears:"20"});expect(result).toEqual({success:true,data:valid})})
})
