import type { CalculatorDefinition } from "@/types/calculator"
import {
  leaveEncashmentFAQs,
  leaveEncashmentRelatedCalculators,
  leaveEncashmentWorkedExample,
} from "./leave-encashment-content"
import { LEAVE_ENCASHMENT_LIMITS, MARGINAL_TAX_RATE_OPTIONS } from "./leave-encashment-schema"

export const leaveEncashmentCalculatorDefinition = {
  id: "leave-encashment-calculator",
  slug: "leave-encashment-calculator",
  title: "Leave Encashment Calculator",
  shortTitle: "Leave Encashment Calculator",
  description: "Estimate the section 10(10AA) tax exemption on leave encashment received at retirement or resignation, with the current ₹25 lakh statutory limit for non-government employees and full exemption for government employees.",
  category: "Finance",
  canonicalPath: "/finance/leave-encashment-calculator",
  inputs: [
    {
      id: "employee-type",
      type: "select",
      label: "Employee type",
      description: "Government (Central/State) employees get full exemption with no ceiling. All other employees use the least-of-four calculation.",
      options: [
        { label: "Non-government", value: "non-government" },
        { label: "Government (Central/State)", value: "government" },
      ],
      required: true,
    },
    {
      id: "last-drawn-basic-salary",
      type: "number",
      label: "Last-drawn basic + DA salary (monthly)",
      description: "Last-drawn monthly basic pay plus dearness allowance forming part of retirement benefits. Used for the leave-at-credit component's daily rate.",
      prefix: "₹",
      min: LEAVE_ENCASHMENT_LIMITS.lastDrawnBasicSalary.min,
      max: LEAVE_ENCASHMENT_LIMITS.lastDrawnBasicSalary.max,
      step: 100,
      required: true,
    },
    {
      id: "average-monthly-salary",
      type: "number",
      label: "10-month average salary (monthly)",
      description: "Average of basic pay plus DA over the 10 months immediately preceding retirement or resignation.",
      prefix: "₹",
      min: LEAVE_ENCASHMENT_LIMITS.averageMonthlySalary.min,
      max: LEAVE_ENCASHMENT_LIMITS.averageMonthlySalary.max,
      step: 100,
      required: true,
    },
    {
      id: "leave-encashment-amount-received",
      type: "number",
      label: "Leave encashment amount received",
      description: "The total lump-sum amount actually paid for encashed leave.",
      prefix: "₹",
      min: LEAVE_ENCASHMENT_LIMITS.leaveEncashmentAmountReceived.min,
      max: LEAVE_ENCASHMENT_LIMITS.leaveEncashmentAmountReceived.max,
      step: 1_000,
      required: true,
    },
    {
      id: "leave-days-encashed",
      type: "number",
      label: "Leave days encashed",
      description: "Total number of unused leave days actually encashed.",
      suffix: "days",
      min: LEAVE_ENCASHMENT_LIMITS.leaveDaysEncashed.min,
      max: LEAVE_ENCASHMENT_LIMITS.leaveDaysEncashed.max,
      step: 1,
      required: true,
    },
    {
      id: "years-of-completed-service",
      type: "number",
      label: "Years of completed service",
      description: "Whole years of completed service with the employer.",
      suffix: "years",
      min: LEAVE_ENCASHMENT_LIMITS.yearsOfCompletedService.min,
      max: LEAVE_ENCASHMENT_LIMITS.yearsOfCompletedService.max,
      step: 1,
      required: true,
    },
    {
      id: "leave-days-earned-per-year",
      type: "number",
      label: "Leave days earned per year",
      description: "Your employer's annual leave-earning rate. The exemption formula recognises at most 30 of these per year of completed service.",
      suffix: "days/year",
      min: LEAVE_ENCASHMENT_LIMITS.leaveDaysEarnedPerYear.min,
      max: LEAVE_ENCASHMENT_LIMITS.leaveDaysEarnedPerYear.max,
      step: 1,
      required: true,
    },
    {
      id: "marginal-tax-rate",
      type: "select",
      label: "Your marginal tax rate",
      description: "An illustrative rate used only to estimate tax on the taxable portion, not part of the exemption formula.",
      options: MARGINAL_TAX_RATE_OPTIONS.map((option) => ({ label: option.label, value: String(option.value) })),
      required: true,
    },
  ],
  formula: {
    title: "Section 10(10AA) exemption formula",
    expression: "Exempt amount = Government employee ? Amount received : least(Amount received, 10-month average salary × 10, Leave at credit × daily rate, ₹25,00,000)",
    description: "Government (Central/State) employees receive full exemption on retirement with no statutory ceiling. For all other employees, the exempt amount is the smallest of: the actual amount received; 10 times the average of the last 10 months' basic + DA salary; the cash equivalent of leave standing to credit (leave days encashed, capped at 30 days for every completed year of service, at the last-drawn daily salary rate); and the current ₹25,00,000 statutory limit.",
    variables: [
      { symbol: "10-month average salary × 10", meaning: "Average of the last 10 months' basic + DA salary, multiplied by 10" },
      { symbol: "Leave at credit", meaning: "min(leave days encashed, min(leave days earned per year, 30) × years of completed service)" },
      { symbol: "Daily rate", meaning: "Last-drawn basic + DA salary ÷ 30" },
      { symbol: "₹25,00,000", meaning: "Current aggregate statutory limit for non-government employees under section 10(10AA)(ii)" },
    ],
  },
  workedExample: leaveEncashmentWorkedExample,
  faqs: leaveEncashmentFAQs,
  relatedCalculators: leaveEncashmentRelatedCalculators,
  metadata: {
    title: "Leave Encashment Calculator: Section 10(10AA) Tax Exemption Estimate",
    description: "Estimate the tax-exempt and taxable portion of leave encashment under section 10(10AA), using the current ₹25 lakh non-government limit and full government-employee exemption.",
    keywords: ["leave encashment calculator", "section 10(10AA)", "leave encashment tax exemption", "leave salary exemption calculator", "leave encashment 25 lakh"],
  },
  status: "published",
} as const satisfies CalculatorDefinition
