import type { CalculatorKnowledgeContent } from "@/types/calculator-content"
export const swpKnowledgeContent={title:"Understand an SWP balance projection",description:"See exactly when withdrawals and growth are applied, how depletion is modelled, and why the result remains an uncertain market scenario.",sections:[
{id:"definition",title:"What is an SWP?",type:"overview",content:[{type:"paragraph",text:"A Systematic Withdrawal Plan withdraws a fixed amount from an existing investment at regular intervals, commonly each month, while the remaining balance stays invested and continues to grow or shrink with the assumed return."}]},
{id:"inputs",title:"Inputs used",type:"input-guide",content:[{type:"list",style:"numbered",items:["Enter the initial investment already available to withdraw from.","Enter the fixed monthly withdrawal amount.","Enter an assumed annual return.","Choose a fixed withdrawal duration, or run the projection until the balance is exhausted."]}]},
{id:"timing",title:"Exact withdrawal and growth timing",type:"how-it-works",content:[{type:"callout",variant:"important",title:"Withdraw first, then grow the remainder",text:"Each month's withdrawal is taken from the opening balance first. Only the balance that remains after the withdrawal receives that month's assumed growth. If the balance cannot cover a full withdrawal, only the available balance is withdrawn and the balance is reported as exhausted in that exact month."}]},
{id:"modes",title:"Fixed duration and until-exhausted modes",type:"how-it-works",content:[{type:"paragraph",text:"Fixed duration projects the selected number of years regardless of outcome; once the balance reaches zero the remaining months simply show zero withdrawal and zero growth. Until-exhausted mode instead stops the projection at the exact month the balance reaches zero. If the withdrawal is at or below the growth the corpus generates, the balance may not be exhausted within a 100-year horizon; the result is reported as capped rather than shown as an unbounded or guessed duration."}]},
{id:"comparison",title:"Comparison with accumulation calculators",type:"comparison",content:[{type:"table",caption:"SWP compared with SIP and Lumpsum",headers:["Calculator","Contribution direction","What it estimates"],rows:[["SIP","Regular money in","Corpus built from repeated contributions"],["Lumpsum","One-time money in","Growth of a single starting amount"],["SWP","Regular money out","How long an existing corpus supports fixed withdrawals"]]}]},
{id:"interpretation",title:"How to read the results",type:"interpretation",content:[{type:"paragraph",text:"Total withdrawn is the sum of every monthly amount actually paid out, including any reduced final withdrawal. Total growth is the estimated return earned on the balance across the whole projection. Together with the remaining balance, these reconcile back to the initial investment."}]},
{id:"mistakes",title:"Common mistakes",type:"common-mistakes",content:[{type:"list",style:"bullet",items:["Assuming a fixed monthly withdrawal is automatically sustainable without checking the exhaustion month.","Treating until-exhausted mode's capped result as a guaranteed duration rather than an horizon limit.","Ignoring that returns are not guaranteed and can be negative in real markets.","Forgetting that this calculator excludes taxation of withdrawals and any product-specific rules."]}]},
{id:"tips",title:"Practical scenario checks",type:"practical-tips",content:[{type:"list",style:"bullet",items:["Compare a fixed duration against until-exhausted mode for the same corpus and withdrawal.","Test a zero expected return to see the corpus decline on withdrawals alone.","Reduce the monthly withdrawal and observe how much longer the corpus lasts."]}]},
{id:"benefits",title:"Potential planning benefits",type:"benefits",content:[{type:"list",style:"bullet",items:["Makes the trade-off between withdrawal size and corpus longevity explicit.","Separates money withdrawn from estimated growth on the remaining balance.","Shows the exact month of exhaustion instead of a vague estimate."]}]},
{id:"limits",title:"Benefits and practical limitations",type:"limitations",content:[{type:"list",style:"bullet",items:["A constant assumed return does not model volatility, sequence-of-return risk, fees, or missed withdrawals.","This calculator does not include taxation of withdrawals, mutual fund exit loads, STT, or other product-specific or statutory rules.","Until-exhausted mode is capped at 100 years and is not a claim that a corpus can literally never run out.","This educational projection is not personalised investment or tax advice."]}]}
],relatedLinks:[{title:"SWP meaning",description:"Read the concise glossary definition.",href:"/glossary/swp"},{title:"SIP Calculator",description:"Estimate the accumulation phase of regular contributions.",href:"/finance/sip-calculator"},{title:"Lumpsum Calculator",description:"Explore a one-time contribution.",href:"/finance/lumpsum-calculator"},{title:"Step-up SIP Calculator",description:"Estimate a SIP that increases contributions yearly.",href:"/finance/step-up-sip-calculator"}]} as const satisfies CalculatorKnowledgeContent
