import type { CalculatorKnowledgeContent } from "@/types/calculator-content"

export const sipKnowledgeContent = {
  title: "Understand your SIP projection", description: "Learn what drives the estimate and which real-world factors remain outside the calculation.",
  sections: [
    { id: "sip-how-to-use", title: "How to use the SIP calculator", type: "input-guide", content: [{ type: "list", style: "numbered", items: ["Enter the planned monthly contribution.", "Enter an expected annual return as an assumption, not a promise.", "Choose the duration and compare invested amount with estimated value."] }] },
    { id: "sip-input-effects", title: "How contribution, return, and duration affect results", type: "how-it-works", content: [{ type: "paragraph", text: "Higher contributions increase the amount invested. A higher assumed return or longer duration raises the projection, but actual market outcomes may differ materially." }] },
    { id: "sip-compounding", title: "Compounding over longer durations", type: "how-it-works", content: [{ type: "paragraph", text: "Projected returns can themselves generate later returns. Time therefore has a nonlinear effect, although market returns do not arrive smoothly or at a guaranteed rate." }] },
    { id: "sip-invested-returns", title: "Invested amount versus estimated returns", type: "interpretation", content: [{ type: "paragraph", text: "Invested amount is the sum of contributions. Estimated returns are the projected value minus those contributions and can be negative in real investments." }] },
    { id: "sip-timing", title: "Beginning-of-month contribution assumption", type: "overview", content: [{ type: "callout", variant: "note", title: "Contribution timing", text: "This calculator assumes each contribution is made at the beginning of the month, giving it one additional month of potential growth. Actual debit and allotment dates may differ." }] },
    { id: "sip-benefits", title: "Benefits of disciplined investing", type: "benefits", content: [{ type: "list", style: "bullet", items: ["Creates a regular contribution habit.", "Spreads contributions across different market dates.", "Makes progress easier to review against a long-term plan."] }] },
    { id: "sip-limitations", title: "Limitations and assumptions", type: "limitations", content: [{ type: "paragraph", text: "The projection uses a constant assumed return. It does not model volatility, inflation, taxes, fees, missed contributions, or product-specific rules unless explicitly stated." }] },
    { id: "sip-mistakes", title: "Common SIP calculation mistakes", type: "common-mistakes", content: [{ type: "list", style: "bullet", items: ["Treating the assumed return as guaranteed.", "Ignoring fees, taxes, inflation, or volatility.", "Confusing annual and monthly return rates.", "Assuming contributions always occur on the modeled date."] }] },
    { id: "sip-tips", title: "Practical tips", type: "practical-tips", content: [{ type: "list", style: "bullet", items: ["Test a range of return assumptions.", "Review invested amount separately from projected gains.", "Use a duration that reflects the decision being explored.", "Revisit assumptions when circumstances change."] }] },
    { id: "sip-comparison", title: "SIP versus lumpsum", type: "comparison", content: [{ type: "table", caption: "SIP and lumpsum investment comparison", headers: ["Factor", "SIP", "Lumpsum"], rows: [["Contribution pattern", "Regular contributions", "One-time contribution"], ["Market timing exposure", "Spread across contribution dates", "Entire amount enters at one point"], ["May suit users who", "Prefer investing from periodic cash flow", "Already have an amount available"], ["Outcome depends on", "Contribution consistency, market path, fees, and taxes", "Market path, holding period, fees, and taxes"]] }] },
  ],
  relatedLinks: [{ title: "Lumpsum Calculator", description: "Compare a one-time investment projection.", href: "/finance/lumpsum-calculator" }, { title: "FD Calculator", description: "Estimate fixed-deposit growth.", href: "/finance/fd-calculator" }, { title: "RD Calculator", description: "Explore regular bank deposits.", href: "/finance/rd-calculator" }, { title: "EMI Calculator", description: "Estimate loan repayments.", href: "/finance/emi-calculator" }],
} as const satisfies CalculatorKnowledgeContent
