import type { CalculatorKnowledgeContent } from "@/types/calculator-content"

export const fdKnowledgeContent = {
  title: "Understand your fixed-deposit estimate", description: "See how principal, term, rate, and compounding shape an estimated maturity amount.",
  sections: [
    { id: "fd-how-to-use", title: "How to use the FD calculator", type: "input-guide", content: [{ type: "list", style: "numbered", items: ["Enter the one-time principal.", "Add the annual rate and deposit duration.", "Choose the stated compounding frequency and review maturity value and interest."] }] },
    { id: "fd-inputs", title: "Principal, rate, duration, and compounding", type: "how-it-works", content: [{ type: "paragraph", text: "Principal is the opening deposit. Rate, duration, and how often interest is added determine the modeled maturity value." }] },
    { id: "fd-compounding", title: "How compounding frequency affects maturity", type: "how-it-works", content: [{ type: "paragraph", text: "When the same nominal rate is used, more frequent compounding generally credits interest to the modeled balance sooner. Bank conventions and product terms can differ." }] },
    { id: "fd-principal-interest", title: "Principal versus interest earned", type: "interpretation", content: [{ type: "paragraph", text: "Principal is the amount deposited. Estimated interest is maturity value minus principal before any applicable tax, deduction, fee, or penalty." }] },
    { id: "fd-benefits", title: "Benefits and common use cases", type: "benefits", content: [{ type: "list", style: "bullet", items: ["Compare deposit terms using consistent assumptions.", "Estimate maturity for a defined time horizon.", "See principal and interest separately."] }] },
    { id: "fd-limitations", title: "Limitations and assumptions", type: "limitations", content: [{ type: "callout", variant: "important", title: "Check the deposit terms", text: "Actual bank calculations may use different day counts, credit dates, rounding, payout options, and product rules. Interest may be taxable under applicable rules." }] },
    { id: "fd-withdrawal", title: "Premature withdrawal considerations", type: "overview", content: [{ type: "paragraph", text: "Early closure may change the applicable rate or introduce a penalty, depending on the product. Confirm liquidity and closure terms with the institution." }] },
    { id: "fd-mistakes", title: "Common FD calculation mistakes", type: "common-mistakes", content: [{ type: "list", style: "bullet", items: ["Using a compounding frequency different from the deposit terms.", "Ignoring premature-withdrawal conditions.", "Assuming all banks apply identical day counts and rounding.", "Treating the pre-tax estimate as the final amount received."] }] },
    { id: "fd-tips", title: "Practical tips", type: "practical-tips", content: [{ type: "list", style: "bullet", items: ["Match every input to the deposit document.", "Compare maturity amounts for the same principal and duration.", "Review interest payout and renewal instructions.", "Keep emergency liquidity needs in mind."] }] },
    { id: "fd-comparison", title: "FD versus RD", type: "comparison", content: [{ type: "table", caption: "Fixed and recurring deposit comparison", headers: ["Factor", "FD", "RD"], rows: [["Deposit pattern", "One-time principal", "Regular instalments"], ["Interest period", "Principal generally earns for the full term", "Each instalment earns for its remaining term"], ["May suit users who", "Have a lump sum available", "Prefer periodic deposits"], ["Actual outcome depends on", "Rate, term, compounding, and bank rules", "Deposit dates, rate, term, compounding, and bank rules"]] }] },
  ],
  relatedLinks: [{ title: "RD Calculator", description: "Compare regular deposits.", href: "/finance/rd-calculator" }, { title: "SIP Calculator", description: "Explore market-linked regular investing.", href: "/finance/sip-calculator" }, { title: "Lumpsum Calculator", description: "Explore one-time investment growth.", href: "/finance/lumpsum-calculator" }, { title: "EMI Calculator", description: "Estimate loan repayments.", href: "/finance/emi-calculator" }],
} as const satisfies CalculatorKnowledgeContent
