import { validateFDInput } from "@/features/calculators/fd/fd-schema"
import type { FDCompoundingFrequency, FDDurationUnit, FDInput } from "@/features/calculators/fd/fd-types"
import { buildCalculatorUrl } from "@/lib/calculator-url"
export const FD_DEFAULT_INPUT:FDInput={principalAmount:100_000,annualInterestRate:7,duration:5,durationUnit:"years",compoundingFrequency:"quarterly"}
type SearchInput=URLSearchParams|Readonly<Record<string,string|string[]|undefined>>
function read(search:SearchInput,key:string){const value=search instanceof URLSearchParams?search.get(key)??undefined:search[key];return Array.isArray(value)?value[0]:value}
export function parseFDUrlState(search:SearchInput,defaults:FDInput=FD_DEFAULT_INPUT):FDInput{const candidate:FDInput={principalAmount:read(search,"amount")===undefined?defaults.principalAmount:Number(read(search,"amount")),annualInterestRate:read(search,"rate")===undefined?defaults.annualInterestRate:Number(read(search,"rate")),duration:read(search,"duration")===undefined?defaults.duration:Number(read(search,"duration")),durationUnit:(read(search,"unit")??defaults.durationUnit) as FDDurationUnit,compoundingFrequency:(read(search,"compounding")??defaults.compoundingFrequency) as FDCompoundingFrequency};const validation=validateFDInput(candidate);if(validation.success)return validation.data;const fallback={...candidate,principalAmount:validation.errors.principalAmount?defaults.principalAmount:candidate.principalAmount,annualInterestRate:validation.errors.annualInterestRate?defaults.annualInterestRate:candidate.annualInterestRate,duration:validation.errors.duration?defaults.duration:candidate.duration,durationUnit:validation.errors.durationUnit?defaults.durationUnit:candidate.durationUnit,compoundingFrequency:validation.errors.compoundingFrequency?defaults.compoundingFrequency:candidate.compoundingFrequency};const checked=validateFDInput(fallback);return checked.success?checked.data:defaults}
export function serializeFDUrlState(input:FDInput){if(!validateFDInput(input).success)throw new RangeError("Invalid FD URL state");return new URLSearchParams({amount:String(input.principalAmount),rate:String(input.annualInterestRate),duration:String(input.duration),unit:input.durationUnit,compounding:input.compoundingFrequency})}
export function buildFDCalculatorUrl(input:FDInput,origin?:string){return buildCalculatorUrl("/finance/fd-calculator",Object.fromEntries(serializeFDUrlState(input)),origin)}
