import type { CalculatorKnowledgeContent } from "@/types/calculator-content"

export const homeLoanEligibilityKnowledgeContent = {
  title: "Understand your home loan eligibility estimate",
  description: "See how the FOIR method turns income and existing obligations into an eligible EMI, loan amount, and property affordability figure.",
  sections: [
    { id: "hle-how-to-use", title: "How to use the Home Loan Eligibility calculator", type: "input-guide", content: [{ type: "list", style: "numbered", items: ["Enter your net (take-home) monthly income.", "Add any existing monthly EMI obligations from other loans.", "Pick a FOIR band, enter the lender's annual interest rate and the loan tenure, and add your own contribution or down payment amount."] }] },
    { id: "hle-foir-method", title: "How the FOIR method works", type: "how-it-works", content: [{ type: "paragraph", text: "The calculator multiplies net monthly income by the chosen FOIR percentage to get a total monthly obligation budget, then subtracts existing EMI obligations to leave the maximum EMI available for a new home loan. That maximum EMI is then run through the reverse of the standard reducing-balance EMI formula, solved for principal instead of payment, to estimate the maximum loan amount the entered rate and tenure could support." }] },
    { id: "hle-reverse-emi", title: "Why a reverse-EMI calculation", type: "how-it-works", content: [{ type: "paragraph", text: "A normal EMI calculation starts from a loan amount and finds the monthly payment. This calculator works backwards from an affordable monthly payment to find the loan amount, using the same rate-and-tenure relationship, so the result stays consistent with what a standard EMI calculator would show for that same loan amount." }] },
    { id: "hle-property-affordability", title: "From loan amount to total property affordability", type: "interpretation", content: [{ type: "paragraph", text: "Total property affordability adds the own contribution or down payment directly to the maximum eligible loan amount. It answers a different question from the eligible loan amount alone: how large a property price this scenario could support in total, combining borrowed and self-funded money." }] },
    { id: "hle-three-numbers", title: "Reading the three headline numbers separately", type: "interpretation", content: [{ type: "paragraph", text: "Max eligible EMI, max eligible loan amount, and total property affordability answer three different questions and are shown separately rather than blended into one figure, so a monthly-budget constraint (EMI) is never confused with a one-time capital figure (loan amount or total affordability)." }] },
    { id: "hle-benefits", title: "Benefits of estimating eligibility first", type: "benefits", content: [{ type: "list", style: "bullet", items: ["Get a rough budget before house-hunting or approaching a lender.", "See how sensitive the eligible amount is to the FOIR band, rate, and tenure chosen.", "Compare the effect of paying down existing EMIs before applying for a home loan."] }] },
    { id: "hle-limitations", title: "Limitations and assumptions", type: "limitations", content: [{ type: "callout", variant: "important", title: "An estimate, not a loan sanction", text: "This tool does not check credit score, employment stability, property valuation, loan-to-value norms, processing fees, or a specific lender's underwriting policy. It applies only the FOIR method and the standard reducing-balance EMI formula in reverse." }] },
    { id: "hle-mistakes", title: "Common eligibility-estimate mistakes", type: "common-mistakes", content: [{ type: "list", style: "bullet", items: ["Entering gross salary instead of net (take-home) monthly income.", "Leaving out existing EMIs on car, personal, or other loans.", "Assuming every lender uses the same FOIR percentage.", "Treating the estimated loan amount as a guaranteed sanction amount."] }] },
    { id: "hle-tips", title: "Practical planning tips", type: "practical-tips", content: [{ type: "list", style: "bullet", items: ["Compare all three FOIR bands rather than relying on a single assumption.", "Check the estimate again after any change in existing EMIs or income.", "Confirm the actual FOIR policy and interest rate with the specific lender before relying on the figure.", "Keep some buffer between the estimated maximum EMI and your actual comfortable monthly commitment."] }] },
    { id: "hle-band-comparison", title: "Comparing the three FOIR bands", type: "comparison", content: [{ type: "table", caption: "Educational comparison of the three FOIR presets", headers: ["Band", "FOIR percentage", "General fit"], rows: [["Conservative", "40%", "Leaves more monthly income unallocated to EMIs; a cautious planning assumption"], ["Standard", "50%", "A commonly used mid-range assumption in home loan eligibility checks"], ["Aggressive", "60%", "Assumes a higher share of income can go to EMIs; leaves less monthly buffer"]] }] },
  ],
  relatedLinks: [
    { title: "EMI Calculator", description: "Calculate the EMI, total interest, and schedule for a specific loan amount.", href: "/finance/emi-calculator" },
    { title: "HRA Calculator", description: "Estimate HRA exemption, which affects net income available for EMIs.", href: "/finance/hra-calculator" },
    { title: "Income Tax Calculator", description: "Estimate take-home income after tax.", href: "/finance/income-tax-calculator" },
  ],
} as const satisfies CalculatorKnowledgeContent
