import type { CalculatorKnowledgeContent } from "@/types/calculator-content"
import { PPF_OFFICIAL_SOURCES } from "./ppf-official-sources"
import { PPF_RATE_CONFIG } from "./ppf-rate-config"

export const ppfKnowledgeContent = {
  title: "Understand the PPF projection", description: "Review the official scheme rules, annual model, timing assumption, constant-rate limitation, and boundaries of this educational estimate.",
  sections: [
    { id: "ppf-what-it-is", title: "What PPF is", type: "overview", content: [{ type: "paragraph", text: "The Public Provident Fund is a Central Government-regulated small-savings scheme governed by the Public Provident Fund Scheme, 2019. The notified rules cover deposits, interest eligibility, maturity, extensions, and account administration." }] },
    { id: "ppf-how-to-use", title: "How to use this calculator", type: "input-guide", content: [{ type: "list", style: "numbered", items: ["Enter one annual contribution in whole rupees and multiples of ₹50.", "Review or edit the assumed constant annual rate.", "Choose 15 years or an illustrative five-year extension duration.", "Compare contributions, estimated interest, maturity, and the annual schedule."] }] },
    { id: "ppf-deposit-rules", title: "Official annual deposit rules", type: "how-it-works", content: [{ type: "paragraph", text: "The scheme allows annual deposits from ₹500 to ₹1,50,000 in multiples of ₹50. Deposits may be made in one lump sum or instalments, subject to the official limits." }] },
    { id: "ppf-official-interest", title: "How official interest eligibility works", type: "how-it-works", content: [{ type: "paragraph", text: "The official scheme uses the lowest account balance between the close of the fifth day and the end of each month for interest eligibility, then credits interest at year-end. A deposit made later can earn less for that financial year." }] },
    { id: "ppf-annual-model", title: "Why this calculator uses an annual model", type: "how-it-works", content: [{ type: "callout", variant: "important", title: "Beginning-of-year assumption", text: "Every annual contribution is modeled at the beginning of the projection year and treated as eligible for a full year's interest. This simplified schedule is illustrative and is not an official account statement." }] },
    { id: "ppf-maturity-timing", title: "Official maturity and extension timing", type: "overview", content: [{ type: "paragraph", text: "Under the scheme, closure is available after fifteen years from the end of the financial year in which the account was opened. Extension with deposits uses further five-year blocks and requires the official option and timing procedure. The selector here counts projection years only; it does not calculate a calendar maturity date, submit an extension, or determine eligibility." }] },
    { id: "ppf-rate-limitation", title: "Reference rate and constant-rate limitation", type: "limitations", content: [{ type: "paragraph", text: `${PPF_RATE_CONFIG.defaultRate}% is the editable reference default verified for ${PPF_RATE_CONFIG.verifiedPeriod.toLowerCase()}. The calculator holds the entered rate constant, while actual government-notified PPF rates may change during the tenure.` }, { type: "callout", variant: "warning", title: "Not a current-rate claim", text: PPF_RATE_CONFIG.verificationNote }] },
    { id: "ppf-read-results", title: "How to read the results", type: "interpretation", content: [{ type: "paragraph", text: "Total contributions are the annual contribution multiplied by duration. Estimated interest is the projected maturity value above those contributions. Maturity is the final schedule balance under the entered assumptions." }] },
    { id: "ppf-benefits", title: "Useful planning questions", type: "benefits", content: [{ type: "list", style: "bullet", items: ["Compare eligible annual contribution levels.", "See the effect of a longer supported duration.", "Separate contributed money from modeled interest.", "Review how each illustrative year builds on the last."] }] },
    { id: "ppf-mistakes", title: "Common projection mistakes", type: "common-mistakes", content: [{ type: "list", style: "bullet", items: ["Treating one rate as fixed for the full real account term.", "Ignoring the monthly fifth-day balance rule.", "Entering a contribution outside official annual limits.", "Reading an illustration as a guaranteed or official maturity value."] }] },
    { id: "ppf-tips", title: "Practical checks", type: "practical-tips", content: [{ type: "list", style: "bullet", items: ["Check the latest official rate notification before acting.", "Consider the actual date of each deposit.", "Verify extension and account-status requirements with the account office.", "Check current tax rules through official sources or a qualified professional."] }] },
    { id: "ppf-comparison", title: "PPF, FD, RD, and CAGR", type: "comparison", content: [{ type: "table", caption: "Conceptual calculator comparison", headers: ["Tool", "What it models", "Key distinction"], rows: [["PPF", "Annual contributions under a government-notified-rate assumption", "Uses a simplified annual timing model"], ["FD", "One lump-sum deposit", "Uses a selected deposit compounding convention"], ["RD", "Regular monthly deposits", "Later instalments earn for less time"], ["CAGR", "Annualised change between endpoints", "Measures past endpoints rather than projecting an account"]] }] },
    { id: "ppf-scope", title: "What the calculator does not model", type: "limitations", content: [{ type: "paragraph", text: "It does not model rate changes, actual monthly deposit timing, missed deposits, discontinuation, revival fees, withdrawals, loans, premature closure, nomination, tax deductions, tax outcomes, or provider and account-office processing." }] },
  ],
  relatedLinks: [{ title: "FD Calculator", description: "Estimate a one-time fixed deposit.", href: "/finance/fd-calculator" }, { title: "RD Calculator", description: "Estimate regular monthly deposits.", href: "/finance/rd-calculator" }, { title: "CAGR Calculator", description: "Measure annualised endpoint growth.", href: "/finance/cagr-calculator" }],
  references: PPF_OFFICIAL_SOURCES.map((source) => ({ title: source.title, organization: source.issuingAuthority, url: source.url })),
} as const satisfies CalculatorKnowledgeContent
