import type { CalculatorDefinition } from "@/types/calculator"
import {
  capitalGainsFAQs,
  capitalGainsRelatedCalculators,
  capitalGainsWorkedExample,
} from "./capital-gains-content"
import { CAPITAL_GAINS_ASSET_TYPE_OPTIONS, CAPITAL_GAINS_LIMITS } from "./capital-gains-schema"

export const capitalGainsCalculatorDefinition = {
  id: "capital-gains-calculator",
  slug: "capital-gains-calculator",
  title: "Capital Gains Calculator (Equity Shares & Mutual Funds)",
  shortTitle: "Capital Gains Calculator",
  description: "Estimate STCG and LTCG tax on listed equity shares and equity-oriented mutual funds across multiple purchase lots, with FIFO lot matching, the pre-2018 grandfathering cost-basis rule, and the pooled ₹1,25,000 LTCG exemption under sections 111A and 112A.",
  category: "Finance",
  canonicalPath: "/finance/capital-gains-calculator",
  inputs: [
    {
      id: "asset-type",
      type: "select",
      label: "Asset type",
      description: "Listed equity shares or equity-oriented mutual fund units — tax treatment is identical; this only changes labeling.",
      options: CAPITAL_GAINS_ASSET_TYPE_OPTIONS.map((option) => ({ label: option.label, value: option.value })),
      required: true,
    },
    {
      id: "lot-units",
      type: "number",
      label: "Units (per purchase lot)",
      description: "Number of units in a purchase lot. Add one row per lot; the calculator also asks for each lot's purchase date, cost per unit, and — only for a lot bought before 31 January 2018 — its fair market value on that date.",
      min: CAPITAL_GAINS_LIMITS.units.min,
      max: CAPITAL_GAINS_LIMITS.units.max,
      step: 1,
      required: true,
    },
    {
      id: "lot-cost-per-unit",
      type: "number",
      label: "Cost per unit (per purchase lot)",
      description: "The price paid per unit for a purchase lot.",
      prefix: "₹",
      min: CAPITAL_GAINS_LIMITS.costPerUnit.min,
      max: CAPITAL_GAINS_LIMITS.costPerUnit.max,
      step: 0.01,
      required: true,
    },
    {
      id: "units-sold",
      type: "number",
      label: "Units sold",
      description: "Total units sold in the single sale event being evaluated, matched against your lots oldest-first (FIFO).",
      min: CAPITAL_GAINS_LIMITS.unitsSold.min,
      max: CAPITAL_GAINS_LIMITS.unitsSold.max,
      step: 1,
      required: true,
    },
    {
      id: "sale-price-per-unit",
      type: "number",
      label: "Sale price per unit",
      description: "The price per unit received in the sale.",
      prefix: "₹",
      min: CAPITAL_GAINS_LIMITS.salePricePerUnit.min,
      max: CAPITAL_GAINS_LIMITS.salePricePerUnit.max,
      step: 0.01,
      required: true,
    },
  ],
  formula: {
    title: "Sections 111A and 112A capital gains formula",
    expression: "Total tax = (pooled STCG × 20%) + (max(0, pooled LTCG − ₹1,25,000) × 12.5%)",
    description: "Units sold are matched against purchase lots oldest-first (FIFO); each matched lot is classified as short-term (STCG, holding period 12 months or less) or long-term (LTCG, holding period more than 12 months). A lot acquired before 31 January 2018 uses a grandfathered cost basis — the higher of its actual cost and the lower of its 31-Jan-2018 fair market value and the sale price — before its gain is computed. All LTCG-classified lot gains are pooled and taxed at 12.5% only above a single ₹1,25,000 annual exemption; all STCG-classified lot gains are pooled and taxed in full at 20%.",
    variables: [
      { symbol: "Pooled STCG", meaning: "Sum of gains from every matched lot classified as short-term" },
      { symbol: "Pooled LTCG", meaning: "Sum of gains from every matched lot classified as long-term, using each lot's grandfathered cost basis where applicable" },
      { symbol: "₹1,25,000", meaning: "Current annual section 112A exemption, applied once against pooled LTCG" },
      { symbol: "Grandfathered cost basis", meaning: "higher(actual cost, lower(FMV as on 31 Jan 2018, sale price)) — pre-31-Jan-2018 lots only" },
    ],
  },
  workedExample: capitalGainsWorkedExample,
  faqs: capitalGainsFAQs,
  relatedCalculators: capitalGainsRelatedCalculators,
  metadata: {
    title: "Capital Gains Calculator: LTCG & STCG Tax on Equity Shares and Mutual Funds",
    description: "Estimate section 111A/112A capital gains tax on equity shares and mutual funds with FIFO lot matching, pre-2018 grandfathering, and the ₹1.25 lakh LTCG exemption.",
    keywords: ["capital gains calculator", "LTCG calculator", "STCG calculator", "section 112A", "section 111A", "grandfathering equity shares", "FIFO capital gains"],
  },
  status: "published",
} as const satisfies CalculatorDefinition
