import { describe,expect,it } from "vitest"
import { parseAndValidateInflationForm,parseInflationNumericText,validateInflationInput } from "../inflation-schema"
const valid={mode:"futureCost" as const,amount:100_000,annualInflationRate:6,years:10}
describe("Inflation validation",()=>{
  it("strictly parses plain decimals, including negatives",()=>{for(const value of ["0","0.01",".5","1000","7.50","-4","-4.5","-.5","-0"])expect(parseInflationNumericText(value)).toBe(Number(value));for(const value of [""," "," 10","10 ","1,000","₹1000","+10","-","--5","5-","1e3","1.",".","NaN","Infinity"])expect(parseInflationNumericText(value)).toBeNull()})
  it("accepts both modes",()=>{expect(validateInflationInput(valid).success).toBe(true);expect(validateInflationInput({...valid,mode:"presentValue"}).success).toBe(true)})
  it("accepts boundary values, including the negative rate floor",()=>{expect(validateInflationInput({...valid,amount:1}).success).toBe(true);expect(validateInflationInput({...valid,amount:100_000_000}).success).toBe(true);expect(validateInflationInput({...valid,annualInflationRate:-10}).success).toBe(true);expect(validateInflationInput({...valid,annualInflationRate:50}).success).toBe(true);expect(validateInflationInput({...valid,years:1}).success).toBe(true);expect(validateInflationInput({...valid,years:50}).success).toBe(true)})
  it.each([{amount:0},{amount:100_000_001},{annualInflationRate:-10.01},{annualInflationRate:50.01},{years:1.5},{years:0},{years:51}])("rejects invalid input %o",change=>expect(validateInflationInput({...valid,...change}).success).toBe(false))
  it("rejects invalid mode and non-finite values",()=>{expect(validateInflationInput({...valid,mode:"other" as never}).success).toBe(false);expect(validateInflationInput({...valid,amount:Infinity}).success).toBe(false);expect(validateInflationInput({...valid,annualInflationRate:Number.NaN}).success).toBe(false)})
  it("rejects a future-cost combination that grows beyond a safe calculation range but allows the same amount in present-value mode",()=>{expect(validateInflationInput({mode:"futureCost",amount:100_000_000,annualInflationRate:50,years:50}).success).toBe(false);expect(validateInflationInput({mode:"presentValue",amount:100_000_000,annualInflationRate:50,years:50}).success).toBe(true)})
  it("rejects malformed form text without losing field-specific errors",()=>{const result=parseAndValidateInflationForm({mode:"futureCost",amount:"1e3",annualInflationRate:" ",years:"1e1"});expect(result.success).toBe(false);if(!result.success)expect(Object.keys(result.errors).sort()).toEqual(["amount","annualInflationRate","years"])})
  it("parses a valid form, including a negative rate",()=>{expect(parseAndValidateInflationForm({mode:"futureCost",amount:"100000",annualInflationRate:"6",years:"10"})).toEqual({success:true,data:valid});expect(parseAndValidateInflationForm({mode:"futureCost",amount:"100000",annualInflationRate:"-4",years:"10"})).toEqual({success:true,data:{...valid,annualInflationRate:-4}})})
})
