import type { CalculatorKnowledgeContent } from "@/types/calculator-content"
export const stepUpSIPKnowledgeContent={title:"Understand a Step-up SIP projection",description:"See how annual increases change contributions and why the result remains an uncertain market scenario.",sections:[
{id:"definition",title:"What is a Step-up SIP?",type:"overview",content:[{type:"paragraph",text:"A Step-up SIP starts with a monthly contribution and increases that contribution once a year. A regular SIP keeps it unchanged."}]},
{id:"inputs",title:"Inputs used",type:"input-guide",content:[{type:"list",style:"numbered",items:["Enter the initial monthly SIP.","Choose a percentage or fixed rupee annual increase.","Enter an assumed annual return and whole-year duration."]}]},
{id:"timing",title:"Exact contribution timing",type:"how-it-works",content:[{type:"callout",variant:"important",title:"Increase after 12 contributions",text:"Months 1–12 use the initial SIP. The first increase applies to month 13, the second to month 25. Contributions are modeled at the beginning of each month."}]},
{id:"methods",title:"Percentage and fixed methods",type:"how-it-works",content:[{type:"paragraph",text:"Percentage mode compounds the monthly contribution by the chosen annual rate. Fixed mode adds the same rupee amount after each 12-contribution block. Internal calculations keep full floating-point precision; displayed currency is rounded."}]},
{id:"comparison",title:"Comparison with a regular SIP",type:"comparison",content:[{type:"paragraph",text:"The comparison uses the same initial contribution, duration, monthly return conversion, and beginning-of-month convention, but applies no step-up. The corpus difference includes additional principal and its estimated growth; it is not all extra return."}]},
{id:"interpretation",title:"How to read the results",type:"interpretation",content:[{type:"paragraph",text:"Separate total invested from estimated returns. The final monthly SIP is the last contribution, and the step-up count includes only increases that affected at least one contribution."}]},
{id:"mistakes",title:"Common mistakes",type:"common-mistakes",content:[{type:"list",style:"bullet",items:["Applying the first increase before month 13.","Calling the full corpus difference extra returns.","Ignoring how quickly percentage increases compound."]}]},
{id:"tips",title:"Practical scenario checks",type:"practical-tips",content:[{type:"list",style:"bullet",items:["Compare percentage and fixed increases.","Test zero step-up against a regular SIP.","Review the final monthly contribution for affordability."]}]},
{id:"benefits",title:"Potential planning benefits",type:"benefits",content:[{type:"list",style:"bullet",items:["Makes future contribution growth explicit.","Shows the contribution path alongside the projected corpus.","Provides a like-for-like regular SIP comparison."]}]},
{id:"limits",title:"Benefits and practical limitations",type:"limitations",content:[{type:"list",style:"bullet",items:["Increasing contributions can align with rising income.","Percentage increases can become difficult to afford over long durations.","A constant assumed return does not model volatility, fees, taxes, inflation, missed payments, or market losses.","This educational scenario is not personalised investment advice or a guaranteed outcome."]}]}
],relatedLinks:[{title:"Step-up SIP meaning",description:"Read the concise glossary definition.",href:"/glossary/step-up-sip"},{title:"Regular SIP Calculator",description:"Estimate a constant monthly SIP.",href:"/finance/sip-calculator"},{title:"Lumpsum Calculator",description:"Explore a one-time contribution.",href:"/finance/lumpsum-calculator"},{title:"CAGR Calculator",description:"Understand annualised growth.",href:"/finance/cagr-calculator"}]} as const satisfies CalculatorKnowledgeContent
