"use client"
import { useState,type FormEvent } from "react"
import { CalculationSummary } from "@/components/calculators/calculation-summary"
import { CalculatorActions } from "@/components/calculators/calculator-actions"
import { CalculatorNumberInput } from "@/components/calculators/calculator-number-input"
import { CalculatorSelectInput } from "@/components/calculators/calculator-select-input"
import { DataTable,type DataTableColumn } from "@/components/calculators/data-table"
import { Button } from "@/components/ui/button"
import { CalculatorResultCard,CalculatorShell } from "@/features/calculators/core"
import { useCalculatorUrlRestore } from "@/features/calculators/core/use-calculator-url-restore"
import { formatIndianCurrency,formatPercentage } from "@/lib/formatters"
import { siteConfig } from "@/lib/site-config"
import type { CalculatorResultItem } from "@/types/calculator"
import { calculateStepUpSIP } from "./calculate-step-up-sip"
import { parseAndValidateStepUpSIPForm,STEP_UP_SIP_LIMITS,type StepUpSIPFormValues } from "./step-up-sip-schema"
import type { StepUpSIPInput,StepUpSIPResult,StepUpSIPScheduleRow,StepUpSIPValidationErrors } from "./step-up-sip-types"
import { buildStepUpSIPCalculatorUrl,parseStepUpSIPUrlState,parseValidStepUpSIPUrlState,STEP_UP_SIP_DEFAULT_INPUT } from "./step-up-sip-url-state"

const toForm=(input:StepUpSIPInput):StepUpSIPFormValues=>({initialMonthlyInvestment:String(input.initialMonthlyInvestment),stepUpMode:input.stepUpMode,annualStepUpValue:String(input.annualStepUpValue),expectedAnnualReturn:String(input.expectedAnnualReturn),durationYears:String(input.durationYears)})
const resultItems=(result:StepUpSIPResult):readonly CalculatorResultItem[]=>[{id:"maturity",label:"Estimated maturity value",value:result.estimatedMaturityValue,displayType:"currency",isPrimary:true},{id:"invested",label:"Total invested",value:result.totalInvested,displayType:"currency"},{id:"returns",label:"Estimated returns",value:result.estimatedReturns,displayType:"currency"},{id:"final",label:"Final monthly SIP",value:result.finalMonthlyInvestment,displayType:"currency"},{id:"steps",label:"Annual step-ups applied",value:result.totalStepUpsApplied,displayType:"number"}]
const columns:readonly DataTableColumn<StepUpSIPScheduleRow>[]=[{header:"Year",cell:row=>row.year},{header:"Monthly SIP",cell:row=>formatIndianCurrency(row.monthlyContributionAtStart)},{header:"Annual contribution",cell:row=>formatIndianCurrency(row.annualContribution)},{header:"Cumulative invested",cell:row=>formatIndianCurrency(row.cumulativeInvestment)},{header:"Estimated year-end value",cell:row=>formatIndianCurrency(row.estimatedYearEndValue)}]

export function StepUpSIPCalculator(){
  const[values,setValues]=useState(()=>toForm(STEP_UP_SIP_DEFAULT_INPUT))
  const[errors,setErrors]=useState<StepUpSIPValidationErrors>({})
  const[calculation,setCalculation]=useState<{input:StepUpSIPInput;result:StepUpSIPResult;date:string}|null>(null)
  const markInteracted=useCalculatorUrlRestore((search)=>{const input=parseStepUpSIPUrlState(search),shared=parseValidStepUpSIPUrlState(search);setValues(toForm(input));if(shared)setCalculation({input:shared,result:calculateStepUpSIP(shared),date:new Intl.DateTimeFormat("en-IN",{dateStyle:"long"}).format(new Date())})})
  function update(field:keyof StepUpSIPFormValues,value:string){
    markInteracted()
    setValues(current=>field==="stepUpMode"?{...current,stepUpMode:value,annualStepUpValue:""}:{...current,[field]:value})
    setErrors(current=>field==="stepUpMode"?{...current,stepUpMode:undefined,annualStepUpValue:undefined}:{...current,[field]:undefined})
    setCalculation(null)
  }
  function submit(event:FormEvent){event.preventDefault();const validation=parseAndValidateStepUpSIPForm(values);if(!validation.success){setErrors(validation.errors);setCalculation(null);return}const result=calculateStepUpSIP(validation.data);setErrors({});setCalculation({input:validation.data,result,date:new Intl.DateTimeFormat("en-IN",{dateStyle:"long"}).format(new Date())});history.replaceState(null,"",buildStepUpSIPCalculatorUrl(validation.data))}
  function reset(){setValues(toForm(STEP_UP_SIP_DEFAULT_INPUT));setErrors({});setCalculation(null);history.replaceState(null,"","/finance/step-up-sip-calculator")}
  const copiedText=calculation?["ThinkCalculator Step-up SIP Estimate",`Initial monthly SIP: ${formatIndianCurrency(calculation.input.initialMonthlyInvestment)}`,`Step-up method: ${calculation.input.stepUpMode==="percentage"?"Percentage":"Fixed amount"}`,`Annual step-up value: ${calculation.input.stepUpMode==="percentage"?formatPercentage(calculation.input.annualStepUpValue):formatIndianCurrency(calculation.input.annualStepUpValue)}`,`Expected annual return assumption: ${formatPercentage(calculation.input.expectedAnnualReturn)}`,`Duration: ${calculation.input.durationYears} years`,`Total invested: ${formatIndianCurrency(calculation.result.totalInvested)}`,`Estimated returns: ${formatIndianCurrency(calculation.result.estimatedReturns)}`,`Estimated maturity value: ${formatIndianCurrency(calculation.result.estimatedMaturityValue)}`,`Final monthly SIP: ${formatIndianCurrency(calculation.result.finalMonthlyInvestment)}`,`Annual step-ups applied: ${calculation.result.totalStepUpsApplied}`,`Regular SIP total invested: ${formatIndianCurrency(calculation.result.regularSipTotalInvested)}`,`Regular SIP estimated returns: ${formatIndianCurrency(calculation.result.regularSipEstimatedReturns)}`,`Regular SIP maturity value: ${formatIndianCurrency(calculation.result.regularSipMaturityValue)}`,`Additional amount invested: ${formatIndianCurrency(calculation.result.additionalInvestment)}`,`Difference in estimated maturity value: ${formatIndianCurrency(calculation.result.maturityValueDifference)}`,"Returns are market-linked estimates and are not guaranteed. Future contribution increases must remain affordable."].join("\n"):""
  return <>
    <div data-calculator-form><CalculatorShell title="Estimate a Step-up SIP" description="Increase a monthly SIP yearly by a percentage or fixed rupee amount."><form className="space-y-5" onSubmit={submit} noValidate>
      <CalculatorNumberInput id="initial" label="Initial monthly SIP" prefix="₹" min={500} max={10_000_000} step={500} value={values.initialMonthlyInvestment} onValueChange={value=>update("initialMonthlyInvestment",value)} error={errors.initialMonthlyInvestment} required/>
      <CalculatorSelectInput id="mode" label="Step-up method" value={values.stepUpMode} onValueChange={value=>update("stepUpMode",value)} options={[{label:"Percentage increase",value:"percentage"},{label:"Fixed rupee increase",value:"fixed"}]} error={errors.stepUpMode} required/>
      <CalculatorNumberInput id="step" label={values.stepUpMode==="percentage"?"Annual step-up percentage":"Annual step-up amount"} description={values.stepUpMode==="percentage"?"10% means the monthly SIP increases by 10% after every 12 contributions.":"₹1,000 means the monthly SIP increases by ₹1,000 after every 12 contributions."} prefix={values.stepUpMode==="fixed"?"₹":undefined} suffix={values.stepUpMode==="percentage"?"%":undefined} min={0} max={values.stepUpMode==="fixed"?STEP_UP_SIP_LIMITS.annualStepUpFixed.max:STEP_UP_SIP_LIMITS.annualStepUpPercentage.max} step={values.stepUpMode==="fixed"?500:0.1} value={values.annualStepUpValue} onValueChange={value=>update("annualStepUpValue",value)} error={errors.annualStepUpValue} required/>
      <CalculatorNumberInput id="return" label="Expected annual return assumption" description="A constant modelling assumption for this scenario, not a forecast or guaranteed return." suffix="%" min={0} max={50} step={0.1} value={values.expectedAnnualReturn} onValueChange={value=>update("expectedAnnualReturn",value)} error={errors.expectedAnnualReturn} required/>
      <CalculatorNumberInput id="years" label="Investment duration" suffix="years" min={1} max={50} step={1} value={values.durationYears} onValueChange={value=>update("durationYears",value)} error={errors.durationYears} required/>
      <div className="flex flex-col gap-3 sm:flex-row"><Button type="submit" size="lg" className="flex-1">Calculate Step-up SIP</Button><Button type="button" size="lg" variant="outline" className="flex-1" onClick={reset}>Reset</Button></div>
    </form></CalculatorShell></div>
    <div className="space-y-6"><CalculatorResultCard title="Step-up SIP estimate" items={calculation?resultItems(calculation.result):[]} emptyTitle="Your estimate will appear here" emptyDescription="Enter the SIP assumptions, then calculate."/>
      {calculation?<><CalculatorActions resultText={copiedText} shareUrl={buildStepUpSIPCalculatorUrl(calculation.input,siteConfig.url)}/><CalculatorResultCard title="Regular SIP comparison" items={[{id:"regular-invested",label:"Regular SIP total invested",value:calculation.result.regularSipTotalInvested,displayType:"currency"},{id:"regular-returns",label:"Regular SIP estimated returns",value:calculation.result.regularSipEstimatedReturns,displayType:"currency"},{id:"regular-value",label:"Regular SIP maturity value",value:calculation.result.regularSipMaturityValue,displayType:"currency"},{id:"additional-invested",label:"Additional amount invested",value:calculation.result.additionalInvestment,displayType:"currency"},{id:"difference",label:"Difference in estimated maturity value",value:calculation.result.maturityValueDifference,displayType:"currency"}]}/><CalculationSummary title="ThinkCalculator Step-up SIP Estimate" calculationDate={calculation.date} disclaimer="Market returns are uncertain and not guaranteed. Ensure future contribution increases remain affordable." items={[{label:"Initial monthly SIP",value:formatIndianCurrency(calculation.input.initialMonthlyInvestment)},{label:"Step-up method",value:calculation.input.stepUpMode==="percentage"?"Percentage":"Fixed amount"},{label:"Annual step-up value",value:calculation.input.stepUpMode==="percentage"?formatPercentage(calculation.input.annualStepUpValue):formatIndianCurrency(calculation.input.annualStepUpValue)},{label:"Expected annual return assumption",value:formatPercentage(calculation.input.expectedAnnualReturn)},{label:"Duration",value:`${calculation.input.durationYears} years`},{label:"Total invested",value:formatIndianCurrency(calculation.result.totalInvested)},{label:"Estimated returns",value:formatIndianCurrency(calculation.result.estimatedReturns)},{label:"Estimated maturity value",value:formatIndianCurrency(calculation.result.estimatedMaturityValue)},{label:"Final monthly SIP",value:formatIndianCurrency(calculation.result.finalMonthlyInvestment)},{label:"Annual step-ups applied",value:String(calculation.result.totalStepUpsApplied)},{label:"Regular SIP maturity value",value:formatIndianCurrency(calculation.result.regularSipMaturityValue)},{label:"Additional amount invested",value:formatIndianCurrency(calculation.result.additionalInvestment)},{label:"Difference in estimated maturity value",value:formatIndianCurrency(calculation.result.maturityValueDifference)}]}/></>:null}
    </div>
    {calculation?<section className="col-span-full" data-calculation-experience aria-labelledby="step-up-sip-schedule-heading"><h2 id="step-up-sip-schedule-heading" className="text-2xl font-semibold">Yearly contribution and growth schedule</h2><p className="mt-3 text-muted-foreground">Each increase starts only after a completed block of 12 contributions. Displayed currency is rounded; calculations retain precision.</p><div className="mt-6"><DataTable caption="Step-up SIP yearly schedule" rows={calculation.result.schedule} columns={columns}/></div></section>:null}
  </>
}
