import { describe, expect, it } from "vitest"
import { availableCalculators } from "@/app/calculators/page"
import { financeCalculators } from "@/app/finance/page"
import sitemap from "@/app/sitemap"
import { calculatorRegistry } from "@/features/calculators/core/calculator-registry"
import { createEditorialSearchDocuments, getGlossaryTermBySlug, getPublicClusterMemberships, getPublicTopicBySlug, getTopicBySlug, getTopicStaticParams, resolveClusterNavigation } from "@/features/content"
import { createCalculatorMetadata, createCanonicalUrl } from "@/lib/seo"
import { popularCalculators } from "@/lib/site-config"
import { calculatePPF } from "../calculate-ppf"
import { createPPFPrintDisclaimer, createPPFResultText } from "../ppf-content"
import { ppfCalculatorDefinition } from "../ppf-definition"
import { ppfKnowledgeContent } from "../ppf-knowledge-content"
import { PPF_OFFICIAL_SOURCES } from "../ppf-official-sources"
import { PPF_RATE_CONFIG } from "../ppf-rate-config"

describe("PPF production integration", () => {
  it("registers one published calculator with clean canonical metadata", () => { expect(calculatorRegistry.filter((item) => item.id === "ppf-calculator")).toEqual([ppfCalculatorDefinition]); expect(createCalculatorMetadata(ppfCalculatorDefinition).alternates?.canonical).toBe(createCanonicalUrl("/finance/ppf-calculator")) })
  it("resolves all related calculators", () => { const paths = new Set(calculatorRegistry.filter((item) => item.status === "published").map((item) => item.canonicalPath)); ppfCalculatorDefinition.relatedCalculators.forEach((item) => expect(paths.has(item.href)).toBe(true)) })
  it("is calculator-search discoverable but excluded from editorial search", () => { expect(popularCalculators.map((item) => item.href)).toContain("/finance/ppf-calculator"); expect(createEditorialSearchDocuments().map((item) => item.canonicalPath)).not.toContain("/finance/ppf-calculator") })
  it("keeps both calculator directories aligned with the published registry", () => { const publishedPaths = calculatorRegistry.filter((item) => item.status === "published").map((item) => item.canonicalPath); const financePaths = calculatorRegistry.filter((item) => item.status === "published" && item.category === "Finance").map((item) => item.canonicalPath); expect(availableCalculators.map((item) => item.href)).toEqual(publishedPaths); expect(financeCalculators.map((item) => item.href)).toEqual(financePaths); expect(availableCalculators.filter((item) => item.href === "/finance/ppf-calculator")).toHaveLength(1); expect(financeCalculators.filter((item) => item.href === "/finance/ppf-calculator")).toHaveLength(1) })
  it("publishes a substantive searchable glossary term", () => { const term = getGlossaryTermBySlug("ppf"); expect(term).toMatchObject({ status: "published", canonicalPath: "/glossary/ppf" }); expect(term!.sections.length).toBeGreaterThanOrEqual(4); expect(createEditorialSearchDocuments().map((item) => item.id)).toContain("glossary-ppf") })
  it("adds Savings membership without publishing the sparse hub or cluster navigation", () => { const savings = getTopicBySlug("savings")!; expect(savings.calculatorIds).toContain("ppf-calculator"); expect(savings.glossaryIds).toContain("glossary-ppf"); expect(getPublicTopicBySlug("savings")).toBeUndefined(); expect(getTopicStaticParams()).not.toContainEqual({ slug: "savings" }); expect(getPublicClusterMemberships("ppf-calculator")).toEqual([]); expect(resolveClusterNavigation("ppf-calculator")).toBeUndefined() })
  it("includes both public routes once and no query or Savings URLs", () => { const urls = sitemap().map((item) => item.url); for (const path of ["/finance/ppf-calculator", "/glossary/ppf"]) expect(urls.filter((url) => url === createCanonicalUrl(path))).toHaveLength(1); expect(urls.some((url) => url.includes("?"))).toBe(false); expect(urls).not.toContain(createCanonicalUrl("/topics/savings")) })
  it("records official references, central rate metadata, and limitations", () => { expect(PPF_RATE_CONFIG.defaultRate).toBeGreaterThan(0); expect(PPF_RATE_CONFIG.effectiveFrom).toMatch(/^\d{4}-\d{2}-\d{2}$/); expect(PPF_RATE_CONFIG.checkedOn).toBe("2026-07-13"); expect(ppfKnowledgeContent.references).toHaveLength(3); PPF_OFFICIAL_SOURCES.forEach((source) => { expect(source.issuingAuthority).not.toBe(""); expect(source.publicationOrEffectiveDate).not.toBe(""); expect(source.ruleUsed).not.toBe(""); expect(source.checkedOn).toBe("2026-07-13") }); const dea = PPF_OFFICIAL_SOURCES.find((source) => source.id === "dea-rates")!; expect(dea.url).toBe("https://dea.gov.in/files/budget_division_documents/RoI_Q1_2627.pdf"); expect(dea.publicationOrEffectiveDate).toBe("Published 2026-03-30 for April-June 2026"); expect(JSON.stringify({ sources: PPF_OFFICIAL_SOURCES, rate: PPF_RATE_CONFIG })).not.toContain("2026-06-30"); const text = JSON.stringify(ppfKnowledgeContent); for (const phrase of ["constant", "not an official", "tax", "withdrawals", "loans"]) expect(text.toLowerCase()).toContain(phrase) })
  it("preserves assumptions and limitations in copied and printed output", () => { const input = { annualContribution: 100_000, assumedAnnualInterestRate: PPF_RATE_CONFIG.defaultRate, durationYears: 15 as const }; const copied = createPPFResultText(input, calculatePPF(input)); const printed = createPPFPrintDisclaimer(); for (const text of [copied, printed]) { expect(text).toContain("reference default"); expect(text).toContain("not a current-rate claim"); expect(text).toContain("full year's interest"); expect(text).toContain("close of the fifth day and month-end") } })
})
