import type { CalculatorKnowledgeContent } from "@/types/calculator-content"

export const rdKnowledgeContent = {
  title: "Understand your recurring-deposit estimate", description: "Learn why deposit timing matters and how regular instalments build the maturity estimate.",
  sections: [
    { id: "rd-how-to-use", title: "How to use the RD calculator", type: "input-guide", content: [{ type: "list", style: "numbered", items: ["Enter the monthly deposit.", "Add the annual rate and duration.", "Choose the compounding frequency and compare total deposited with estimated interest."] }] },
    { id: "rd-contribution-duration", title: "Monthly contribution and duration", type: "how-it-works", content: [{ type: "paragraph", text: "The total deposited equals the monthly contribution multiplied by the number of months. Longer terms add more instalments and give earlier deposits more time to earn interest." }] },
    { id: "rd-different-periods", title: "Why instalments earn for different periods", type: "how-it-works", content: [{ type: "paragraph", text: "Every instalment is treated separately. The first remains deposited for the full term, while each later instalment has one month less to earn interest." }] },
    { id: "rd-timing", title: "Beginning-of-month assumption", type: "overview", content: [{ type: "callout", variant: "note", title: "Deposit timing", text: "This calculator assumes deposits are made at the beginning of each month. Actual bank deposit dates and product rules may produce a different maturity value." }] },
    { id: "rd-deposited-interest", title: "Total deposited versus interest earned", type: "interpretation", content: [{ type: "paragraph", text: "Total deposited is the sum of instalments. Estimated interest is the maturity amount above that total before any applicable tax, fee, or penalty." }] },
    { id: "rd-benefits", title: "Benefits and common use cases", type: "benefits", content: [{ type: "list", style: "bullet", items: ["Explore a regular savings pattern.", "Estimate a maturity amount for a chosen term.", "Separate deposits from estimated interest."] }] },
    { id: "rd-limitations", title: "Limitations and assumptions", type: "limitations", content: [{ type: "paragraph", text: "Actual results may differ because of deposit dates, missed instalments, day-count conventions, rounding, compounding rules, taxes, and institution-specific terms." }] },
    { id: "rd-closure", title: "Missed instalments and premature closure", type: "overview", content: [{ type: "paragraph", text: "A missed deposit or early closure may change interest or trigger charges under the product rules. Check these terms directly with the institution." }] },
    { id: "rd-mistakes", title: "Common RD calculation mistakes", type: "common-mistakes", content: [{ type: "list", style: "bullet", items: ["Assuming every instalment earns for the full term.", "Ignoring the modeled beginning-of-month timing.", "Using the wrong compounding frequency.", "Ignoring missed-instalment or closure terms."] }] },
    { id: "rd-tips", title: "Practical tips", type: "practical-tips", content: [{ type: "list", style: "bullet", items: ["Match rate, duration, and compounding to the product document.", "Review total deposits separately from interest.", "Check the scheduled debit date.", "Understand missed-instalment and closure conditions."] }] },
    { id: "rd-comparison", title: "RD versus FD", type: "comparison", content: [{ type: "table", caption: "Recurring and fixed deposit comparison", headers: ["Factor", "RD", "FD"], rows: [["Deposit pattern", "Regular instalments", "One-time principal"], ["Interest period", "Each instalment has a different remaining term", "Principal generally earns for the full term"], ["May suit users who", "Prefer periodic deposits", "Have a lump sum available"], ["Actual outcome depends on", "Dates, rate, compounding, and bank rules", "Rate, term, compounding, and bank rules"]] }] },
  ],
  relatedLinks: [{ title: "FD Calculator", description: "Compare a one-time deposit.", href: "/finance/fd-calculator" }, { title: "SIP Calculator", description: "Explore regular market-linked investing.", href: "/finance/sip-calculator" }, { title: "Lumpsum Calculator", description: "Explore one-time investment growth.", href: "/finance/lumpsum-calculator" }, { title: "EMI Calculator", description: "Estimate loan repayments.", href: "/finance/emi-calculator" }],
} as const satisfies CalculatorKnowledgeContent
