import { validateRDInput } from "@/features/calculators/rd/rd-schema"
import type { RDCompoundingFrequency, RDDurationUnit, RDInput } from "@/features/calculators/rd/rd-types"
import { buildCalculatorUrl } from "@/lib/calculator-url"
export const RD_DEFAULT_INPUT:RDInput={monthlyDeposit:5_000,annualInterestRate:7,duration:5,durationUnit:"years",compoundingFrequency:"quarterly"}
type SearchInput=URLSearchParams|Readonly<Record<string,string|string[]|undefined>>
function read(search:SearchInput,key:string){const value=search instanceof URLSearchParams?search.get(key)??undefined:search[key];return Array.isArray(value)?value[0]:value}
export function parseRDUrlState(search:SearchInput,defaults:RDInput=RD_DEFAULT_INPUT):RDInput{const candidate:RDInput={monthlyDeposit:read(search,"monthly")===undefined?defaults.monthlyDeposit:Number(read(search,"monthly")),annualInterestRate:read(search,"rate")===undefined?defaults.annualInterestRate:Number(read(search,"rate")),duration:read(search,"duration")===undefined?defaults.duration:Number(read(search,"duration")),durationUnit:(read(search,"unit")??defaults.durationUnit) as RDDurationUnit,compoundingFrequency:(read(search,"compounding")??defaults.compoundingFrequency) as RDCompoundingFrequency};const validation=validateRDInput(candidate);if(validation.success)return validation.data;const fallback={...candidate,monthlyDeposit:validation.errors.monthlyDeposit?defaults.monthlyDeposit:candidate.monthlyDeposit,annualInterestRate:validation.errors.annualInterestRate?defaults.annualInterestRate:candidate.annualInterestRate,duration:validation.errors.duration?defaults.duration:candidate.duration,durationUnit:validation.errors.durationUnit?defaults.durationUnit:candidate.durationUnit,compoundingFrequency:validation.errors.compoundingFrequency?defaults.compoundingFrequency:candidate.compoundingFrequency};const checked=validateRDInput(fallback);return checked.success?checked.data:defaults}
export function serializeRDUrlState(input:RDInput){if(!validateRDInput(input).success)throw new RangeError("Invalid RD URL state");return new URLSearchParams({monthly:String(input.monthlyDeposit),rate:String(input.annualInterestRate),duration:String(input.duration),unit:input.durationUnit,compounding:input.compoundingFrequency})}
export function buildRDCalculatorUrl(input:RDInput,origin?:string){return buildCalculatorUrl("/finance/rd-calculator",Object.fromEntries(serializeRDUrlState(input)),origin)}
