import type { CalculatorKnowledgeContent } from "@/types/calculator-content"
import { GST_RATE_CONFIG } from "./gst-rate-config"

export const gstKnowledgeContent = {
  title: "Understand GST-inclusive and exclusive arithmetic",
  description: "Learn what this calculator does, how addition and removal differ, how the selected tax heads are displayed, and which regulatory and invoice questions remain outside its scope.",
  sections: [
    { id: "gst-overview", title: "What GST is at a high level", type: "overview", content: [{ type: "paragraph", text: "Goods and Services Tax is an indirect-tax framework applied to taxable supplies under applicable law. This page explains only percentage arithmetic; it does not decide whether a transaction is taxable or which classification, notification, or place-of-supply rule applies." }] },
    { id: "gst-calculator-scope", title: "What this calculator does", type: "input-guide", content: [{ type: "list", style: "numbered", items: ["Enter an amount and choose whether it is exclusive or inclusive of GST.", "Use a common preset or enter a custom percentage.", "Select intra-State or inter-State arithmetic yourself.", "Review the exclusive value, GST, inclusive value, and selected tax-head breakdown."] }] },
    { id: "gst-exclusive-inclusive", title: "Exclusive versus inclusive amounts", type: "how-it-works", content: [{ type: "paragraph", text: "A GST-exclusive amount is the taxable base before the entered GST percentage is added. A GST-inclusive amount contains both that base and the embedded GST. The GST Portal's GSTR-1 guide describes total invoice value as inclusive of taxes, while taxable value is a distinct field." }] },
    { id: "gst-add", title: "How to add GST", type: "how-it-works", content: [{ type: "paragraph", text: "Multiply the exclusive value by the entered percentage divided by 100. Add the resulting GST amount to the exclusive value to obtain the inclusive value." }] },
    { id: "gst-remove", title: "How to remove embedded GST", type: "how-it-works", content: [{ type: "paragraph", text: "Divide the inclusive value by 1 plus the entered rate as a decimal. The difference between the inclusive value and the derived exclusive value is the embedded GST." }, { type: "callout", variant: "important", title: "Do not simply subtract the rate", text: "An 18% addition is measured against the smaller exclusive base. Subtracting 18% of the larger inclusive value therefore does not reverse the original calculation; dividing by 1.18 does." }] },
    { id: "gst-tax-heads", title: "Intra-State and inter-State tax heads", type: "interpretation", content: [{ type: "paragraph", text: "For the intra-State selection, this calculator splits total GST equally into CGST and SGST/UTGST. For the inter-State selection, it shows the total as IGST. CBIC material supports the high-level distinction, but this calculator does not determine place of supply or infer the correct supply type." }] },
    { id: "gst-rates", title: "Presets, custom rates, and classification", type: "limitations", content: [{ type: "paragraph", text: "The 5%, 12%, 18%, and 28% buttons are commonly encountered arithmetic presets represented in official schedules; they are not exhaustive and are not recommendations for any named supply. The 0% button is only a calculation option and does not declare a supply nil-rated, zero-rated, exempt, or outside GST." }, { type: "callout", variant: "warning", title: "Verify the applicable rate", text: GST_RATE_CONFIG.applicabilityNotice }] },
    { id: "gst-custom-rate", title: "Why a custom rate is available", type: "input-guide", content: [{ type: "paragraph", text: "A custom rate lets you test generic percentage arithmetic, including a value such as 7.5%, without presenting it as an official preset or suggesting legal applicability." }] },
    { id: "gst-examples", title: "Worked arithmetic examples", type: "overview", content: [{ type: "table", caption: "Examples checked against the production calculation", headers: ["Scenario", "Input", "Result"], rows: [["Add, intra-State", "₹1,000 exclusive at 18%", "₹180 GST; ₹1,180 inclusive; ₹90 CGST and ₹90 SGST/UTGST"], ["Remove, inter-State", "₹1,180 inclusive at 18%", "₹1,000 exclusive; ₹180 IGST"], ["Zero-rate option", "₹1,000 at 0%", "₹0 GST; exclusive and inclusive values are equal"], ["Custom arithmetic", "₹1,000 at 7.5%", "₹75 GST; ₹1,075 inclusive"], ["Amount with paise", "₹999.99 at 18%", "Full precision is retained before display rounding"]] }] },
    { id: "gst-rounding", title: "Rounding and invoice differences", type: "limitations", content: [{ type: "paragraph", text: "The calculator keeps unrounded numeric values and rounds each displayed total and tax head independently. Displayed CGST and SGST/UTGST halves can therefore differ by one paise from the separately rounded total; no hidden round-off adjustment is applied. Actual invoice totals can differ because of applicable rounding rules, accounting-system conventions, multiple items, discounts, and valuation adjustments." }] },
    { id: "gst-useful-checks", title: "Useful arithmetic checks", type: "benefits", content: [{ type: "list", style: "bullet", items: ["Separate an entered inclusive total into its base and GST components.", "Compare how the same entered rate changes exclusive and inclusive values.", "See the selected tax-head split without inferring the legal supply type.", "Share a complete validated arithmetic scenario for review."] }] },
    { id: "gst-practical-tips", title: "Practical checks before using a result", type: "practical-tips", content: [{ type: "list", style: "bullet", items: ["Confirm whether the amount entered is exclusive or inclusive.", "Verify the applicable classification and rate using current official material.", "Confirm place-of-supply treatment outside this calculator.", "Reconcile invoice-level rounding in the accounting or invoicing system actually used."] }] },
    { id: "gst-mode-comparison", title: "Add GST versus remove GST", type: "comparison", content: [{ type: "table", caption: "Calculation mode comparison", headers: ["Mode", "Entered amount", "Primary result"], rows: [["Add GST", "Exclusive taxable value", "Inclusive value after adding GST"], ["Remove GST", "Inclusive value containing GST", "Derived exclusive taxable value"]] }] },
    { id: "gst-exclusions", title: "Tax and compliance exclusions", type: "limitations", content: [{ type: "paragraph", text: "The calculation excludes compensation cess and other cess, reverse charge, input tax credit, composition levy, TDS/TCS, discounts and valuation adjustments, invoice-line rounding, e-invoicing, place-of-supply determination, return liability, filing, penalties, and legal or compliance decisions." }] },
    { id: "gst-mistakes", title: "Common mistakes", type: "common-mistakes", content: [{ type: "list", style: "bullet", items: ["Treating a preset as a rate-classification answer.", "Subtracting the percentage directly from an inclusive value.", "Letting an address assumption stand in for a place-of-supply decision.", "Reading a two-decimal display as invoice-ready legal computation."] }] },
    { id: "gst-disclaimer", title: "Educational disclaimer", type: "limitations", content: [{ type: "callout", variant: "warning", title: "Arithmetic only", text: "This calculator is educational and is not tax or legal advice, an invoice generator, a filing tool, or a substitute for current official guidance, accounting controls, or qualified professional review." }] },
  ],
  relatedLinks: [],
  references: GST_RATE_CONFIG.sources.map((source) => ({ title: `${source.title} — checked ${source.checkedOn}`, organization: source.issuingAuthority, url: source.url })),
} as const satisfies CalculatorKnowledgeContent
