import type { EditorialContentItem } from "@/types/editorial-content"
import { editorialAuthor as author, editorialCategories as category, editorialTags as tag } from "./content-types"

const meta = (title: string, description: string, keywords: readonly string[]) => ({ title, description, keywords })
export const contentRegistry: readonly EditorialContentItem[] = [
  {
    id: "blog-understanding-loan-emi", slug: "understanding-loan-emi", type: "blog", title: "Understanding Loan EMI: Principal, Interest, and Tenure",
    description: "Understand how loan principal, interest rate, and tenure determine EMI and total borrowing cost.", excerpt: "An EMI turns a loan into regular monthly repayments. Learn what changes the payment and why a lower EMI does not always mean a lower total cost.",
    category: category.loans, tags: [tag.emi, tag.loans, tag.financialPlanning], author, canonicalPath: "/blog/understanding-loan-emi", publishedAt: "2026-07-12", status: "published", estimatedReadingMinutes: 4,
    sections: [
      { id: "what-is-an-emi", title: "What is an EMI?", blocks: [{ type: "paragraph", text: "An equated monthly instalment is the scheduled amount paid each month toward a loan. Each payment contains principal repayment and interest, though their proportions change over the tenure." }] },
      { id: "three-main-inputs", title: "The three inputs that shape EMI", blocks: [{ type: "list", ordered: false, items: ["Principal is the amount borrowed.", "Interest rate is the annual cost applied by the lender.", "Tenure is the time allowed for repayment."] }, { type: "callout", title: "Compare total cost too", text: "A longer tenure can reduce the monthly EMI while increasing the total interest paid." }] },
      { id: "how-interest-changes", title: "How the repayment changes over time", blocks: [{ type: "paragraph", text: "For a reducing-balance loan, interest is calculated on the outstanding balance. Early instalments generally contain more interest; later instalments generally repay more principal." }] },
      { id: "worked-example", title: "A practical example", blocks: [{ type: "paragraph", text: "For a ₹5,00,000 loan at 10% a year for five years, an EMI calculator estimates the monthly payment using the monthly rate and 60 payments. The displayed schedule helps separate principal from interest." }, { type: "paragraph", text: "Try different values in the EMI Calculator.", links: [{ text: "EMI Calculator", href: "/finance/emi-calculator" }] }] },
    ],
    faqs: [{ question: "Does a longer tenure always help?", answer: "It may lower the monthly payment, but it can increase total interest. Compare affordability and total cost." }, { question: "Can the actual EMI differ from an estimate?", answer: "Yes. Lender rounding, fees, rate changes, and payment timing can affect actual figures." }, { question: "Is interest the same in every instalment?", answer: "The EMI can stay level while the interest and principal portions change as the balance reduces." }],
    relatedContent: [{ title: "How to Use an EMI Calculator", href: "/guides/how-to-use-emi-calculator", description: "A step-by-step guide to entering and interpreting loan inputs." }], relatedCalculators: [{ title: "EMI Calculator", href: "/finance/emi-calculator", description: "Estimate monthly repayment, total interest, and an amortisation schedule." }], metadata: meta("Understanding Loan EMI: Principal, Interest, and Tenure", "Learn how principal, interest rate, and tenure affect loan EMI and total repayment cost.", ["loan EMI", "principal and interest", "loan tenure"]), disclaimer: "Loan calculations are estimates for education and comparison, not personalised financial advice. Confirm terms and charges with the lender."
  },
  {
    id: "blog-sip-vs-lumpsum", slug: "sip-vs-lumpsum", type: "blog", title: "SIP vs Lumpsum: Understanding the Difference", description: "Compare regular SIP contributions with a one-time lumpsum investment and understand the assumptions behind growth estimates.", excerpt: "SIP and lumpsum describe when money is invested. Neither method guarantees a return, and the useful comparison begins with cash flow, time, and risk.", category: category.investing, tags: [tag.sip, tag.mutualFunds, tag.compounding], author, canonicalPath: "/blog/sip-vs-lumpsum", publishedAt: "2026-07-12", status: "published", estimatedReadingMinutes: 4,
    sections: [
      { id: "two-contribution-patterns", title: "Two contribution patterns", blocks: [{ type: "table", caption: "SIP and lumpsum at a glance", headers: ["Feature", "SIP", "Lumpsum"], rows: [["Contribution", "Regular amount", "One-time amount"], ["Time in market", "Each instalment has a different period", "The full amount starts together"], ["Return", "Market-linked and uncertain", "Market-linked and uncertain"]] }] },
      { id: "how-sip-estimates-work", title: "How SIP estimates work", blocks: [{ type: "paragraph", text: "A SIP projection compounds each periodic contribution for its remaining time. Earlier contributions normally have longer to grow than later ones." }] },
      { id: "how-lumpsum-estimates-work", title: "How lumpsum estimates work", blocks: [{ type: "paragraph", text: "A lumpsum projection compounds one starting amount for the full selected period. The result is sensitive to both the assumed annual return and duration." }, { type: "callout", title: "Projection, not promise", text: "A steady assumed return is a calculation aid. Real market returns vary and may be negative." }] },
      { id: "compare-like-for-like", title: "Compare like with like", blocks: [{ type: "paragraph", text: "Use the SIP Calculator for regular contributions and the Lumpsum Calculator for a one-time investment. Compare invested amount separately from estimated gain.", links: [{ text: "SIP Calculator", href: "/finance/sip-calculator" }, { text: "Lumpsum Calculator", href: "/finance/lumpsum-calculator" }] }] },
    ], faqs: [{ question: "Is SIP always safer than lumpsum?", answer: "No. Both can carry market risk. SIP spreads contribution dates but does not prevent loss." }, { question: "Which calculator should I use?", answer: "Use SIP for regular contributions and lumpsum for one starting investment." }, { question: "Are projected returns guaranteed?", answer: "No. The assumed return produces an illustration, not a forecast or guarantee." }], relatedContent: [{ title: "How to Estimate SIP Growth", href: "/guides/how-to-estimate-sip-growth", description: "Understand the inputs and limits of a SIP projection." }], relatedCalculators: [{ title: "SIP Calculator", href: "/finance/sip-calculator", description: "Project regular investment growth." }, { title: "Lumpsum Calculator", href: "/finance/lumpsum-calculator", description: "Project one-time investment growth." }], metadata: meta("SIP vs Lumpsum: Understanding the Difference", "Understand how SIP and lumpsum contribution patterns differ and how to compare their projected growth.", ["SIP vs lumpsum", "SIP", "lumpsum investment"]), disclaimer: "Investment projections are illustrative and do not account for every cost, tax, or market movement. Returns are not guaranteed."
  },
  {
    id: "guide-use-emi", slug: "how-to-use-emi-calculator", type: "guide", title: "How to Use an EMI Calculator", description: "Learn how to enter loan amount, interest rate, and tenure, then interpret EMI, total interest, and the repayment schedule.", excerpt: "An EMI calculator makes loan scenarios easier to compare when its inputs match the lender's quotation. This guide explains each field and the results it produces.", category: category.loans, tags: [tag.emi, tag.loans, tag.financialPlanning], author, canonicalPath: "/guides/how-to-use-emi-calculator", publishedAt: "2026-07-12", status: "published", estimatedReadingMinutes: 4,
    sections: [
      { id: "gather-the-inputs", title: "1. Gather the loan inputs", blocks: [{ type: "list", ordered: false, items: ["Loan principal after any down payment", "Annual interest rate quoted by the lender", "Repayment tenure in years or months"] }] },
      { id: "enter-the-values", title: "2. Enter the values", blocks: [{ type: "paragraph", text: "Open the EMI Calculator and enter the principal, annual rate, and tenure. Use the same units as the form labels.", links: [{ text: "EMI Calculator", href: "/finance/emi-calculator" }] }] },
      { id: "read-the-results", title: "3. Read the results", blocks: [{ type: "table", caption: "Key EMI results", headers: ["Result", "What it means"], rows: [["Monthly EMI", "Estimated scheduled monthly payment"], ["Total interest", "Estimated interest across the tenure"], ["Total payment", "Principal plus estimated interest"]] }] },
      { id: "test-scenarios", title: "4. Test sensible scenarios", blocks: [{ type: "paragraph", text: "For example, keep the loan amount and rate unchanged, then compare a five-year tenure with a seven-year tenure. The longer option may reduce EMI but increase total interest." }, { type: "callout", title: "Use lender documents for decisions", text: "The calculator does not include every fee, insurance charge, penalty, or rate-reset rule." }] },
    ], faqs: [{ question: "Should I enter a flat or reducing rate?", answer: "The calculator uses a reducing-balance method. Confirm how the lender quotes and applies its rate." }, { question: "Can I use the calculator for floating-rate loans?", answer: "You can estimate using a current rate, but future rate changes will alter the schedule." }, { question: "Why might a lender show a different EMI?", answer: "Differences can come from payment dates, rounding, fees, rate conventions, or product terms." }], relatedContent: [{ title: "Understanding Loan EMI", href: "/blog/understanding-loan-emi", description: "Learn how principal, interest, and tenure interact." }], relatedCalculators: [{ title: "EMI Calculator", href: "/finance/emi-calculator", description: "Estimate repayment and review the amortisation schedule." }], metadata: meta("How to Use an EMI Calculator", "A practical guide to EMI calculator inputs, results, comparisons, and limitations.", ["how to use EMI calculator", "EMI calculation", "loan calculator guide"]), disclaimer: "The result is an estimate and is not a loan offer. Verify repayment figures and all charges with the lender."
  },
  {
    id: "guide-estimate-sip", slug: "how-to-estimate-sip-growth", type: "guide", title: "How to Estimate SIP Growth", description: "Use contribution, return, and duration assumptions to estimate SIP growth while recognising the limits of a steady-return projection.", excerpt: "A SIP growth estimate separates the money contributed from a hypothetical gain. Its value depends on transparent assumptions, not on predicting the market.", category: category.investing, tags: [tag.sip, tag.compounding, tag.financialPlanning], author, canonicalPath: "/guides/how-to-estimate-sip-growth", publishedAt: "2026-07-12", status: "published", estimatedReadingMinutes: 4,
    sections: [
      { id: "choose-contribution", title: "1. Choose a monthly contribution", blocks: [{ type: "paragraph", text: "Start with an amount that represents the regular contribution you want to model. The calculator treats it as a monthly cash flow, not a promise to invest." }] },
      { id: "set-return-assumption", title: "2. Set an annual return assumption", blocks: [{ type: "paragraph", text: "The annual rate is converted into a periodic rate for the projection. Try more than one reasonable assumption to see how sensitive the result is." }, { type: "callout", title: "Avoid false precision", text: "A calculator can apply a rate precisely, but it cannot make an uncertain market return certain." }] },
      { id: "select-duration", title: "3. Select the duration", blocks: [{ type: "paragraph", text: "Longer durations add more contributions and more potential compounding periods. Later contributions have less time to grow than earlier ones." }] },
      { id: "interpret-output", title: "4. Interpret the output", blocks: [{ type: "paragraph", text: "Use the SIP Calculator to compare total contributions, estimated gain, and projected value. A Lumpsum Calculator is appropriate when the full amount is invested once.", links: [{ text: "SIP Calculator", href: "/finance/sip-calculator" }, { text: "Lumpsum Calculator", href: "/finance/lumpsum-calculator" }] }, { type: "list", ordered: false, items: ["Check the invested amount first.", "Treat estimated returns as scenario output.", "Compare multiple rates and durations."] }] },
    ], faqs: [{ question: "Does the SIP calculator predict mutual fund returns?", answer: "No. It applies your assumed rate consistently to illustrate a scenario." }, { question: "Why do later contributions earn less in the estimate?", answer: "They have fewer compounding periods before the selected end date." }, { question: "Should I include inflation?", answer: "The displayed future value is nominal. Consider purchasing power separately when planning." }], relatedContent: [{ title: "SIP vs Lumpsum", href: "/blog/sip-vs-lumpsum", description: "Compare regular and one-time contribution patterns." }], relatedCalculators: [{ title: "SIP Calculator", href: "/finance/sip-calculator", description: "Estimate regular contribution growth." }, { title: "Lumpsum Calculator", href: "/finance/lumpsum-calculator", description: "Estimate one-time investment growth." }], metadata: meta("How to Estimate SIP Growth", "Learn how contribution, return, and duration assumptions shape a SIP growth estimate.", ["estimate SIP growth", "SIP calculator guide", "compound growth"]), disclaimer: "SIP results are illustrative. Market-linked returns vary, may be negative, and are not guaranteed."
  },
  {
    id: "draft-fd-vs-rd", slug: "choosing-between-fd-and-rd", type: "blog", title: "Choosing Between FD and RD", description: "Draft comparison of fixed and recurring deposits.", excerpt: "A draft editorial item used to validate public-content exclusion.", category: category.savings, tags: [tag.compounding], author, canonicalPath: "/blog/choosing-between-fd-and-rd", publishedAt: "2026-07-12", status: "draft", estimatedReadingMinutes: 1, sections: [{ id: "draft-section", title: "Draft section", blocks: [{ type: "paragraph", text: "This unpublished draft is intentionally unavailable on public routes." }] }], faqs: [], relatedContent: [], relatedCalculators: [], metadata: meta("Choosing Between FD and RD", "Draft comparison of FD and RD contribution patterns.", ["FD", "RD"])
  },
] as const

export function getContentBySlug(slug: string, type?: "blog" | "guide") { return contentRegistry.find((item) => item.slug === slug && (!type || item.type === type)) }
export function getPublishedContent() { return contentRegistry.filter((item) => item.status === "published") }
export function getContentByType(type: "blog" | "guide") { return getPublishedContent().filter((item) => item.type === type) }
export function getContentByCategory(slug: string) { return getPublishedContent().filter((item) => item.category.slug === slug) }
export function getContentByTag(slug: string) { return getPublishedContent().filter((item) => item.tags.some((itemTag) => itemTag.slug === slug)) }
export function getRelatedContent(item: EditorialContentItem) { const paths = new Set(item.relatedContent.map((link) => link.href)); return getPublishedContent().filter((candidate) => paths.has(candidate.canonicalPath)) }
export function getRelatedCalculators(item: EditorialContentItem) { return item.relatedCalculators }
