import type { GlossaryTerm } from "@/types/glossary-content"

const calculator = (title: string, href: string, description: string) => ({ title, href, description })
const metadata = (term: string, description: string, keywords: readonly string[]) => ({ title: `${term}: Meaning and Examples`, description, keywords })
const term = (value: Omit<GlossaryTerm, "id" | "canonicalPath">): GlossaryTerm => ({ ...value, id: `glossary-${value.slug}`, canonicalPath: `/glossary/${value.slug}` })

export const glossaryRegistry: readonly GlossaryTerm[] = [
  term({ slug: "emi", term: "EMI", shortDefinition: "EMI, or equated monthly instalment, is a scheduled monthly loan payment containing principal and interest.", status: "published", sections: [
    { id: "meaning", title: "What EMI means", blocks: [{ type: "paragraph", text: "An equated monthly instalment is the amount scheduled for payment each month over a loan tenure. For a reducing-balance loan, the payment may remain level while the principal and interest portions change." }] },
    { id: "calculation", title: "How EMI relates to a calculation", blocks: [{ type: "paragraph", text: "EMI depends mainly on the amount borrowed, the periodic interest rate, and the number of repayments. A higher principal or rate generally increases EMI; a longer tenure can lower EMI while increasing total interest." }] },
    { id: "example", title: "Simple example", blocks: [{ type: "paragraph", text: "A ₹5,00,000 loan repaid over five years has 60 monthly instalments. The EMI calculation applies the monthly rate to the outstanding balance across those instalments." }] },
    { id: "limits", title: "What an EMI estimate may omit", blocks: [{ type: "callout", title: "Estimate, not a loan offer", text: "Fees, insurance, payment dates, rate resets, lender rounding, and product rules can change the actual repayment." }] },
  ], relatedCalculators: [calculator("EMI Calculator", "/finance/emi-calculator", "Estimate EMI, total interest, and the repayment schedule.")], relatedContent: [calculator("Understanding Loan EMI", "/blog/understanding-loan-emi", "Understand principal, interest, and tenure.")], metadata: metadata("EMI", "Learn what EMI means, how it is calculated, and what can make an actual loan repayment differ.", ["EMI meaning", "equated monthly instalment", "loan EMI"]) }),
  term({ slug: "principal", term: "Principal", shortDefinition: "Principal is the original amount borrowed or invested, before interest, returns, fees, or repayments are applied.", status: "published", sections: [
    { id: "meaning", title: "What principal means", blocks: [{ type: "paragraph", text: "In a loan, principal is the amount owed before interest. In an investment or deposit, it commonly means the amount contributed before growth is added." }] },
    { id: "loan-relationship", title: "Principal in loan calculations", blocks: [{ type: "paragraph", text: "Loan interest is calculated using the principal or outstanding balance. As repayments reduce the outstanding principal, the interest portion generally falls in a reducing-balance schedule." }] },
    { id: "investment-relationship", title: "Principal in savings and investments", blocks: [{ type: "paragraph", text: "The starting principal and later contributions form the invested amount. Estimated gain should be shown separately so that growth is not confused with money contributed." }] },
    { id: "example", title: "Simple example", blocks: [{ type: "paragraph", text: "If you borrow ₹2,00,000, the initial loan principal is ₹2,00,000. Interest and eligible charges are separate from that starting amount." }] },
  ], relatedCalculators: [calculator("EMI Calculator", "/finance/emi-calculator", "See how principal affects EMI and total interest."), calculator("Lumpsum Calculator", "/finance/lumpsum-calculator", "Project growth from one starting amount.")], relatedContent: [calculator("Understanding Loan EMI", "/blog/understanding-loan-emi", "See principal within a loan repayment.")], metadata: metadata("Principal", "Understand principal in loans, deposits, and investments with clear calculation examples.", ["principal meaning", "loan principal", "investment principal"]) }),
  term({ slug: "interest-rate", term: "Interest Rate", shortDefinition: "An interest rate is the percentage used to calculate the cost of borrowing or the growth of eligible savings over a stated period.", status: "published", sections: [
    { id: "meaning", title: "What an interest rate means", blocks: [{ type: "paragraph", text: "A rate must be read together with its time period and calculation method. An annual rate is not simply the amount charged or earned every month." }] },
    { id: "borrowing", title: "Interest rate in borrowing", blocks: [{ type: "paragraph", text: "For reducing-balance loans, periodic interest is applied to the outstanding balance. The quoted rate, compounding convention, and repayment timing affect the result." }] },
    { id: "saving", title: "Interest rate in deposits", blocks: [{ type: "paragraph", text: "Deposit projections apply a stated rate using a compounding frequency. Actual maturity can differ because of product rules, taxes, premature closure, and rounding." }] },
    { id: "example", title: "Simple example", blocks: [{ type: "paragraph", text: "A 10% annual input in a monthly loan calculation is converted to a periodic rate before the repayment formula is applied." }] },
  ], relatedCalculators: [calculator("EMI Calculator", "/finance/emi-calculator", "Compare loan scenarios at different rates."), calculator("FD Calculator", "/finance/fd-calculator", "Estimate fixed-deposit growth at an assumed rate.")], relatedContent: [calculator("How to Use an EMI Calculator", "/guides/how-to-use-emi-calculator", "Enter and interpret a loan rate.")], metadata: metadata("Interest Rate", "Learn how interest rates affect loan and deposit calculations and why the calculation method matters.", ["interest rate meaning", "annual interest rate", "loan interest"]) }),
  term({ slug: "tenure", term: "Tenure", shortDefinition: "Tenure is the agreed or selected length of time for a loan, deposit, or investment calculation.", status: "published", sections: [
    { id: "meaning", title: "What tenure means", blocks: [{ type: "paragraph", text: "Tenure expresses duration, often in months or years. The unit matters because calculation formulas use a specific number of payment or compounding periods." }] },
    { id: "loans", title: "Tenure in loan calculations", blocks: [{ type: "paragraph", text: "A longer loan tenure usually spreads principal across more payments. This can reduce EMI but may increase total interest when other assumptions stay unchanged." }] },
    { id: "investments", title: "Tenure in growth calculations", blocks: [{ type: "paragraph", text: "A longer duration adds potential compounding periods. It does not guarantee a return, especially for market-linked investments." }] },
    { id: "example", title: "Simple example", blocks: [{ type: "paragraph", text: "Five years corresponds to 60 monthly periods in a monthly EMI calculation." }] },
  ], relatedCalculators: [calculator("EMI Calculator", "/finance/emi-calculator", "Compare payment and total interest across tenures."), calculator("SIP Calculator", "/finance/sip-calculator", "Explore contribution periods and projected growth.")], relatedContent: [calculator("How to Use an EMI Calculator", "/guides/how-to-use-emi-calculator", "Learn how to enter loan tenure.")], metadata: metadata("Tenure", "Understand tenure in loan and investment calculations, including its effect on EMI and growth periods.", ["tenure meaning", "loan tenure", "investment duration"]) }),
  term({ slug: "sip", term: "SIP", shortDefinition: "A SIP, or systematic investment plan, is a pattern of investing a chosen amount at regular intervals.", status: "published", sections: [
    { id: "meaning", title: "What SIP means", blocks: [{ type: "paragraph", text: "SIP describes regular contributions, commonly monthly. It is a contribution method, not a guaranteed-return product." }] },
    { id: "calculation", title: "How a SIP projection works", blocks: [{ type: "paragraph", text: "A projection compounds each contribution for its remaining time. Earlier contributions generally have more periods to grow than later contributions." }] },
    { id: "example", title: "Simple example", blocks: [{ type: "paragraph", text: "A monthly contribution of ₹5,000 for one year produces ₹60,000 of total contributions before any estimated gain or loss." }] },
    { id: "risk", title: "Important limitation", blocks: [{ type: "callout", title: "Returns are not guaranteed", text: "A steady assumed return is useful for a scenario, but real market returns vary and may be negative." }] },
  ], relatedCalculators: [calculator("SIP Calculator", "/finance/sip-calculator", "Estimate regular contribution growth.")], relatedContent: [calculator("How to Estimate SIP Growth", "/guides/how-to-estimate-sip-growth", "Interpret contribution, rate, and duration inputs."), calculator("SIP vs Lumpsum", "/blog/sip-vs-lumpsum", "Compare regular and one-time contributions.")], metadata: metadata("SIP", "Learn what SIP means, how regular investment projections work, and why estimated returns are not guaranteed.", ["SIP meaning", "systematic investment plan", "SIP calculation"]) }),
  term({ slug: "compounding", term: "Compounding", shortDefinition: "Compounding is growth calculated on an amount that can include previously added interest or returns.", status: "published", sections: [
    { id: "meaning", title: "What compounding means", blocks: [{ type: "paragraph", text: "With compounding, an earlier gain can become part of the base for a later calculation. The rate, time, contribution timing, and compounding frequency all matter." }] },
    { id: "frequency", title: "Why frequency matters", blocks: [{ type: "paragraph", text: "Annual, quarterly, monthly, and other frequencies divide time differently. Comparisons should use consistent rate conventions and contribution timing." }] },
    { id: "example", title: "Simple example", blocks: [{ type: "paragraph", text: "If ₹10,000 grows by 10% in one period, it becomes ₹11,000. Applying the same illustrative rate to that new amount in a second period produces ₹12,100." }] },
    { id: "limits", title: "Projection limits", blocks: [{ type: "callout", title: "A formula is not a forecast", text: "Market returns do not normally arrive at a fixed rate. Fees, taxes, withdrawals, and rate changes can alter actual results." }] },
  ], relatedCalculators: [calculator("FD Calculator", "/finance/fd-calculator", "Explore deposit compounding."), calculator("Lumpsum Calculator", "/finance/lumpsum-calculator", "Project growth of a starting amount.")], relatedContent: [calculator("How to Estimate SIP Growth", "/guides/how-to-estimate-sip-growth", "See compounding in a regular-contribution scenario.")], metadata: metadata("Compounding", "Understand compounding, frequency, and the limits of fixed-rate growth projections.", ["compounding meaning", "compound growth", "compound interest"]) }),
  term({ slug: "cagr", term: "CAGR", shortDefinition: "CAGR, or compound annual growth rate, is the constant annual rate that connects a beginning value to an ending value over a period.", status: "published", sections: [
    { id: "meaning", title: "What CAGR means", blocks: [{ type: "paragraph", text: "Compound annual growth rate expresses an endpoint change as one smooth annual compound rate. It is useful when comparing growth over periods of different lengths, provided the underlying values are comparable." }] },
    { id: "calculation", title: "How CAGR is calculated", blocks: [{ type: "paragraph", text: "Divide the ending value by the positive beginning value, raise that ratio to one divided by the number of years, subtract one, and convert the result to a percentage." }] },
    { id: "example", title: "Simple example", blocks: [{ type: "paragraph", text: "A value that rises from ₹1,00,000 to ₹1,61,051 over five years has a CAGR of 10%. Its total return is about 61.05%: total return measures the full endpoint change, while CAGR annualises that change over five years." }] },
    { id: "negative", title: "Negative CAGR and complete loss", blocks: [{ type: "paragraph", text: "If the ending value is lower than the beginning value, CAGR is negative. If the ending value is zero, the endpoint investment has lost 100% of its beginning value." }] },
    { id: "limits", title: "What CAGR does not show", blocks: [{ type: "callout", title: "A smooth rate hides the path", text: "CAGR does not show volatility or the order of annual gains and losses. A simple endpoint CAGR also does not adjust for contributions or withdrawals made during the period, and historical CAGR does not predict future returns." }] },
  ], relatedCalculators: [calculator("CAGR Calculator", "/finance/cagr-calculator", "Calculate annualised endpoint growth, total return, and gain or loss."), calculator("Lumpsum Calculator", "/finance/lumpsum-calculator", "Project a one-time amount under an assumed return.")], relatedContent: [calculator("SIP vs Lumpsum", "/blog/sip-vs-lumpsum", "Compare regular and one-time contribution patterns."), calculator("How to Estimate SIP Growth", "/guides/how-to-estimate-sip-growth", "Understand assumptions behind investment growth estimates.")], metadata: metadata("CAGR", "Learn what CAGR means, how compound annual growth rate is calculated, and why it differs from total return.", ["CAGR meaning", "compound annual growth rate", "annualised return", "CAGR formula"]) }),
  term({ slug: "ppf", term: "PPF", shortDefinition: "PPF, or Public Provident Fund, is a Central Government-regulated small-savings scheme with official deposit, interest, maturity, and extension rules.", status: "published", sections: [
    { id: "meaning", title: "What PPF means", blocks: [{ type: "paragraph", text: "The Public Provident Fund operates under the Public Provident Fund Scheme, 2019. It is an account-based savings scheme whose rate is notified by the Central Government and may change over time." }] },
    { id: "deposits", title: "Deposits and timing", blocks: [{ type: "paragraph", text: "The scheme permits ₹500 to ₹1,50,000 in a financial year in multiples of ₹50, paid as a lump sum or instalments. Monthly interest eligibility depends on the lowest balance between the close of the fifth day and month-end." }] },
    { id: "calculation", title: "How a PPF projection relates to the account", blocks: [{ type: "paragraph", text: "A simplified calculator can add annual contributions and compound them at an assumed rate. An actual account uses notified rates and monthly balance eligibility, so timing and future rate changes can alter the result." }] },
    { id: "tenure", title: "Maturity and extensions", blocks: [{ type: "paragraph", text: "The scheme permits closure after fifteen years from the end of the financial year in which the account was opened. Continuation with deposits uses further five-year blocks and is subject to the official option and timing procedure." }] },
    { id: "limits", title: "Projection limitation", blocks: [{ type: "callout", title: "Illustration, not a guarantee", text: "Holding one editable rate constant across 15 to 40 years does not predict future notified rates or produce an official account statement." }] },
  ], relatedCalculators: [calculator("PPF Calculator", "/finance/ppf-calculator", "Estimate annual contributions, interest, and maturity under disclosed assumptions."), calculator("FD Calculator", "/finance/fd-calculator", "Compare a one-time deposit projection."), calculator("RD Calculator", "/finance/rd-calculator", "Compare regular monthly deposits.")], relatedContent: [], metadata: metadata("PPF", "Understand Public Provident Fund deposit rules, interest timing, maturity, extensions, and constant-rate projection limits.", ["PPF meaning", "Public Provident Fund", "PPF deposit limits", "PPF maturity"]) }),
  term({ slug: "gst", term: "GST", shortDefinition: "GST, or Goods and Services Tax, is an indirect-tax framework; a GST calculation relates an exclusive taxable value, a tax amount, and an inclusive value at an entered rate.", status: "published", sections: [
    { id: "meaning", title: "What GST means", blocks: [{ type: "paragraph", text: "Goods and Services Tax applies under statutory classification, notification, valuation, and place-of-supply rules. A percentage calculator can show arithmetic but cannot decide whether GST applies or which rate is correct for a particular supply." }] },
    { id: "exclusive-inclusive", title: "Exclusive and inclusive values", blocks: [{ type: "paragraph", text: "A GST-exclusive taxable value is the base before GST is added. An inclusive value contains that base plus GST. To reverse an inclusive calculation, divide by one plus the rate as a decimal rather than subtracting the rate from the inclusive total." }] },
    { id: "tax-heads", title: "CGST, SGST, UTGST, and IGST", blocks: [{ type: "paragraph", text: "At a high level, intra-State arithmetic commonly shows CGST with SGST or UTGST, while inter-State arithmetic shows IGST. Legal treatment depends on place-of-supply and transaction facts, which a simple calculator does not determine." }] },
    { id: "example", title: "Simple arithmetic example", blocks: [{ type: "paragraph", text: "At an entered 18% rate, adding GST to an exclusive value of ₹1,000 produces ₹180 GST and an inclusive value of ₹1,180. Removing embedded GST from ₹1,180 at the same rate recovers ₹1,000." }] },
    { id: "limits", title: "Rate and compliance limits", blocks: [{ type: "callout", title: "Classification must be verified", text: "Common percentage presets are not an exhaustive rate list or a classification answer. Verify current official sources or seek qualified advice. Cess, input tax credit, reverse charge, filing, penalties, invoice rules, and other compliance matters require separate treatment." }] },
  ], relatedCalculators: [calculator("GST Calculator", "/business/gst-calculator", "Add or remove an entered GST percentage and view selected tax-head arithmetic.")], relatedContent: [], metadata: metadata("GST", "Understand GST-exclusive and inclusive values, CGST/SGST/UTGST and IGST arithmetic, and rate-classification limits.", ["GST meaning", "Goods and Services Tax", "GST inclusive", "CGST SGST IGST"]) }),
  term({ slug: "gratuity", term: "Gratuity", shortDefinition: "Gratuity is a statutory employment benefit that may become payable when qualifying employment ends, commonly calculated from last-drawn eligible wages and completed service.", status: "published", sections: [
    { id: "meaning", title: "What gratuity means in India", blocks: [{ type: "paragraph", text: "Gratuity is governed by the Code on Social Security, 2020 for covered cases under the current central framework. Relevant provisions took effect from 21 November 2025. It is linked to an employee's qualifying termination event, last-drawn eligible wages, and continuous service rather than being an automatic percentage of gross salary." }] },
    { id: "wages", title: "Last-drawn eligible wages", blocks: [{ type: "paragraph", text: "The statutory wage definition includes basic pay, dearness allowance, and retaining allowance, if any, and specifies exclusions plus a 50% add-back rule. The correct figure may therefore require payroll review; gross salary or CTC should not be substituted without checking the definition." }] },
    { id: "service", title: "Completed service and the part-year rule", blocks: [{ type: "paragraph", text: "For the standard amount, every completed service year is counted and a remaining part-year is added only when it is in excess of six months. Exactly six additional months does not add a counted year, while seven additional months does." }] },
    { id: "calculation", title: "Standard monthly rated calculation", blocks: [{ type: "paragraph", text: "For a regular monthly rated employee, fifteen days' wages are calculated by dividing last-drawn eligible monthly wages by 26 and multiplying by 15. That amount is multiplied by counted service years, then the statutory ceiling is applied." }] },
    { id: "ceiling-example", title: "Ceiling and simple example", blocks: [{ type: "paragraph", text: "The currently confirmed statutory ceiling is ₹20,00,000. For example, ₹50,000 of eligible monthly wages and 7 years 7 months gives 8 counted years and a formula amount of about ₹2,30,769.23, below the ceiling." }] },
    { id: "eligibility", title: "Eligibility is a separate legal question", blocks: [{ type: "callout", title: "Do not treat the formula as an entitlement decision", text: "The ordinary rule, coverage, continuous service, death, disablement, fixed-term employment, working-journalist treatment, seasonal or piece-rated work, better contractual terms, exemptions, forfeiture, and changes in law can alter the legal outcome." }] },
    { id: "sources", title: "Official context and review date", blocks: [{ type: "paragraph", text: "This definition was reviewed on 13 July 2026 against the Code on Social Security, 2020, commencement notification S.O. 5319(E), the Social Security (Central) Rules, 2026, Ministry Labour Codes FAQs dated 30 December 2025, Additional FAQs as on 16 March 2026, and S.O. 1420(E). The 2018 ceiling notification was issued under the repealed 1972 Act; the Code's savings clause continues non-conflicting prior notifications, and the December 2025 FAQs confirm ₹20 lakh as the current maximum. The calculator page provides the source links." }] },
  ], relatedCalculators: [calculator("Gratuity Calculator", "/finance/gratuity-calculator", "Estimate the standard monthly rated amount, service count, and ceiling effect.")], relatedContent: [], metadata: metadata("Gratuity", "Understand gratuity in India, eligible wages, completed service, the 15/26 formula, current ceiling, and eligibility caveats.", ["gratuity meaning", "gratuity formula India", "eligible wages gratuity", "gratuity service rule"]) }),
  term({ slug: "maturity-value", term: "Maturity Value", shortDefinition: "Maturity value is the amount a deposit calculation estimates at the end of its selected tenure.", status: "draft", sections: [], relatedCalculators: [], relatedContent: [], metadata: metadata("Maturity Value", "Draft definition of maturity value.", ["maturity value"]) }),
  term({ slug: "step-up-sip", term: "Step-up SIP", shortDefinition: "A Step-up SIP is a monthly investment plan whose contribution increases after each completed block of 12 contributions by a selected percentage or fixed amount.", status: "published", sections: [
    { id: "meaning", title: "What a Step-up SIP means", blocks: [{ type: "paragraph", text: "A regular SIP keeps its contribution constant. A Step-up SIP begins with one monthly amount and raises future monthly contributions annually." }] },
    { id: "methods", title: "Percentage and fixed increases", blocks: [{ type: "paragraph", text: "Percentage mode compounds the contribution each year. Fixed mode adds the same rupee amount each year. Months 1 to 12 use the initial amount; the first increase affects month 13." }] },
    { id: "example", title: "Simple example", blocks: [{ type: "paragraph", text: "A ₹10,000 SIP with a 10% annual step-up contributes ₹10,000 in months 1 to 12 and ₹11,000 in months 13 to 24." }] },
    { id: "risk", title: "Affordability and market risk", blocks: [{ type: "callout", title: "Scenario, not a promise", text: "Future contributions may become difficult to sustain, and assumed market returns are not guaranteed. A larger projected corpus includes additional money invested." }] },
  ], relatedCalculators: [calculator("Step-up SIP Calculator", "/finance/step-up-sip-calculator", "Estimate percentage or fixed annual increases and compare with a regular SIP."), calculator("SIP Calculator", "/finance/sip-calculator", "Estimate a constant monthly SIP.")], relatedContent: [], metadata: metadata("Step-up SIP", "Understand Step-up SIP meaning, annual timing, percentage and fixed increases, and market-risk limits.", ["step up SIP meaning", "top up SIP", "annual SIP increase"]) }),
  term({ slug: "swp", term: "SWP", shortDefinition: "An SWP, or Systematic Withdrawal Plan, is a pattern of withdrawing a fixed amount from an existing investment at regular intervals while the remaining balance stays invested.", status: "published", sections: [
    { id: "meaning", title: "What SWP means", blocks: [{ type: "paragraph", text: "A Systematic Withdrawal Plan withdraws a chosen amount, commonly monthly, from an existing corpus. It is a withdrawal pattern, not a guaranteed-income product, and the remaining balance continues to be exposed to market movement." }] },
    { id: "timing", title: "Withdrawal and growth timing", blocks: [{ type: "paragraph", text: "A projection commonly withdraws the amount first, then applies that period's assumed growth only to the balance left afterwards. If the balance cannot cover a full withdrawal, only the remaining balance is paid out, and the balance is treated as exhausted at that point." }] },
    { id: "example", title: "Simple example", blocks: [{ type: "paragraph", text: "A ₹50,00,000 corpus with a ₹35,000 fixed monthly withdrawal and an assumed 8% annual return can be projected month by month to see how the balance changes and whether it lasts a chosen duration." }] },
    { id: "risk", title: "Sustainability and market risk", blocks: [{ type: "callout", title: "Scenario, not a guarantee", text: "A withdrawal amount above the corpus's sustainable growth will deplete it faster than expected. Assumed returns are not guaranteed, and this figure excludes taxation of withdrawals and product-specific rules." }] },
  ], relatedCalculators: [calculator("SWP Calculator", "/finance/swp-calculator", "Estimate how long a lumpsum investment supports fixed monthly withdrawals."), calculator("SIP Calculator", "/finance/sip-calculator", "Estimate the accumulation phase of regular contributions.")], relatedContent: [], metadata: metadata("SWP", "Understand SWP meaning, withdrawal and growth timing, exhaustion, and market-risk limits.", ["SWP meaning", "systematic withdrawal plan", "SWP calculation"]) }),
] as const

export function getPublishedGlossaryTerms() { return glossaryRegistry.filter((item) => item.status === "published") }
export function getGlossaryTermBySlug(slug: string) { return glossaryRegistry.find((item) => item.slug === slug) }
export function getGlossaryStaticParams() { return getPublishedGlossaryTerms().map((item) => ({ slug: item.slug })) }
