import type { CalculatorKnowledgeContent } from "@/types/calculator-content"

export const emiKnowledgeContent = {
  title: "Understand your EMI estimate",
  description: "Use the estimate alongside the repayment schedule and total borrowing cost when comparing loan scenarios.",
  sections: [
    { id: "emi-how-to-use", title: "How to use the EMI calculator", type: "input-guide", content: [{ type: "list", style: "numbered", items: ["Enter the amount you expect to borrow.", "Add the annual interest rate quoted for the loan.", "Choose the repayment tenure and review the EMI, total interest, and schedule together."] }] },
    { id: "emi-input-effects", title: "How amount, rate, and tenure affect EMI", type: "how-it-works", content: [{ type: "paragraph", text: "A larger loan or higher rate generally raises the EMI and total interest. A longer tenure may lower the monthly payment but usually increases the time over which interest is charged." }] },
    { id: "emi-schedule", title: "How to interpret the amortization schedule", type: "interpretation", content: [{ type: "paragraph", text: "Each row separates the payment into principal and interest and shows the remaining balance. Small differences from a lender schedule can arise from rounding and payment dates." }] },
    { id: "emi-principal-interest", title: "Principal versus interest", type: "interpretation", content: [{ type: "paragraph", text: "On a reducing balance loan, early instalments commonly contain more interest because the outstanding principal is higher. The principal share generally grows as the balance falls." }] },
    { id: "emi-benefits", title: "Benefits of estimating EMI", type: "benefits", content: [{ type: "list", style: "bullet", items: ["Compare different amounts, rates, and tenures consistently.", "See total interest rather than focusing only on the monthly payment.", "Prepare questions for a lender before applying."] }] },
    { id: "emi-limitations", title: "Limitations and assumptions", type: "limitations", content: [{ type: "callout", variant: "important", title: "An estimate, not a lender quote", text: "Fees, insurance, changing rates, lender-specific methods, rounding, and exact payment dates are not included unless explicitly shown." }] },
    { id: "emi-mistakes", title: "Common EMI calculation mistakes", type: "common-mistakes", content: [{ type: "list", style: "bullet", items: ["Entering a monthly rate as an annual rate or vice versa.", "Comparing only EMI while ignoring total interest.", "Leaving processing fees, insurance, or other charges out of the broader cost comparison.", "Assuming every lender uses identical dates and rounding."] }] },
    { id: "emi-tips", title: "Practical affordability checks", type: "practical-tips", content: [{ type: "list", style: "bullet", items: ["Compare the payment with stable income and existing obligations.", "Leave room for irregular expenses and changes in income.", "Test more than one rate and tenure instead of relying on a single scenario.", "Review prepayment terms directly with the lender."] }, { type: "callout", variant: "note", title: "No universal ratio", text: "An affordable EMI depends on the borrower’s full circumstances; one EMI-to-income percentage is not suitable for everyone." }] },
    { id: "emi-rate-comparison", title: "Fixed versus floating interest rates", type: "comparison", content: [{ type: "table", caption: "Educational comparison of fixed and floating loan rates", headers: ["Factor", "Fixed rate", "Floating rate"], rows: [["Payment predictability", "Usually more predictable during the fixed period", "May change when the benchmark or lender rate changes"], ["Rate movement", "Does not usually benefit from market-rate falls during the fixed period", "May rise or fall according to the loan terms"], ["Best fit depends on", "Need for predictability and contract terms", "Capacity to handle payment or tenure changes and contract terms"]] }] },
  ],
  relatedLinks: [
    { title: "SIP Calculator", description: "Explore regular investment projections.", href: "/finance/sip-calculator" }, { title: "FD Calculator", description: "Estimate fixed-deposit maturity.", href: "/finance/fd-calculator" }, { title: "RD Calculator", description: "Estimate recurring-deposit maturity.", href: "/finance/rd-calculator" }, { title: "Lumpsum Calculator", description: "Explore one-time investment growth.", href: "/finance/lumpsum-calculator" },
  ],
} as const satisfies CalculatorKnowledgeContent
